### PR TITLE
Issue1421 python no energy plus

### PR DESCRIPTION
**Pull request by mwetter**
@AntoineGautier 

This replaces https://github.com/lbl-srg/modelica-buildings/pull/1422
because it contains the Spawn development files which are not ready to be merged to the master.
The wrong commit that contains these files is 1ef4779af74ef29b829ea73f55d01b157d16d6bf

Todo:
- [x] Replace `asprintf` which `saveAppend`
- [x] Remove the entry `/home/agautier/miniconda2` with an environment variable that can be set before invoking the compilation
- [x] Remove the entry `C:\Users\agautier/Miniconda2` with an environment variable that can be set before invoking the compilation

Commit e0cc957  in this branch was created by running
```bash
set -e
# Last commit that does not have EnergyPlus files
git checkout 69d7c83f8164bd49c38454ab90c90c329216d627
# New working branch
git checkout -b issue1421_python_noEnergyPlus
#   Below is the list obtained from
#   git checkout issue issue1421_python && git diff --name-only origin/master | grep ython
git checkout issue1421_python Buildings/Resources/C-Sources/python27Wrapper.c
git checkout issue1421_python Buildings/Resources/Library/linux32/libModelicaBuildingsPython2.7.so
git checkout issue1421_python Buildings/Resources/Library/linux64/libModelicaBuildingsPython2.7.so
git checkout issue1421_python Buildings/Resources/Library/win32/ModelicaBuildingsPython2.7.dll
git checkout issue1421_python Buildings/Resources/Library/win32/ModelicaBuildingsPython2.7.lib
git checkout issue1421_python Buildings/Resources/Library/win32/python2.7.dll
git checkout issue1421_python Buildings/Resources/Library/win64/ModelicaBuildingsPython2.7.dll
git checkout issue1421_python Buildings/Resources/Library/win64/ModelicaBuildingsPython2.7.lib
git checkout issue1421_python Buildings/Resources/Library/win64/python2.7.dll
git checkout issue1421_python Buildings/Resources/src/python/Makefile.linux
git checkout issue1421_python Buildings/Resources/src/python/Makefile.windows.bat
git checkout issue1421_python Buildings/Resources/src/python/asprintf.h
git checkout issue1421_python Buildings/Resources/src/python/pythonInterpreter.c
git checkout issue1421_python Buildings/Resources/src/python/pythonInterpreter.h
git checkout issue1421_python Buildings/Resources/src/python/pythonObjectStructure.h
git checkout issue1421_python Buildings/Resources/src/python/testProgram
git checkout issue1421_python Buildings/Resources/src/python/testProgram.c
git checkout issue1421_python Buildings/Resources/src/python/testProgram.h
git checkout issue1421_python Buildings/Utilities/IO/Python27/Functions/BaseClasses/exchange.mo
git checkout issue1421_python Buildings/Utilities/IO/Python27/Functions/exchange.mo
# Get top-level package file with revision notes
git checkout issue1421_python Buildings/package.mo

```

### CODE REVIEW

**Comment by AntoineGautier** [comment]
I integrated the code of `saveAppend` (from the branch `issue1129_energyPlus_zone_fmiSignature`) and had to change the function signature to allow for calling `ModelicaFormatError` so I renamed it `saveAppendModelica`. Not sure if it is the best approach though.

**Comment by mwetter** [comment]
@AntoineGautier : The integration of `saveAppendModelica` looks good, except for the change I made in https://github.com/lbl-srg/modelica-buildings/pull/1433/commits/de15a48c5228a520e71305124a8b08469f601388

**Comment by AntoineGautier** [comment]
@mwetter My conclusions based on testing `Buildings.Utilities.IO.Python27.Functions.Examples.Exchange`. 

- The compilation succeeds on the master and development branch with a local installation of JModelica see` *_local.log` attached.
- The compilation fails with JModelica docker only for the development branch see `*_docker.log` attached.

[master_docker.log](https://github.com/lbl-srg/modelica-buildings/files/3263880/master_docker.log)
[issue1421_docker.log](https://github.com/lbl-srg/modelica-buildings/files/3263881/issue1421_docker.log)
[issue1421_local.log](https://github.com/lbl-srg/modelica-buildings/files/3263882/issue1421_local.log)
[master_local.log](https://github.com/lbl-srg/modelica-buildings/files/3263883/master_local.log)

**Comment by mwetter** [comment]
@AntoineGautier : I suggest we merge this if the latest tests pass, and then try to address the problem mentioned in https://github.com/lbl-srg/modelica-buildings/issues/1421#issuecomment-510215078

**Pull request merged**
