### PR TITLE
Issue735 data center chiller wse

### LINKED ISSUE #735: add model for data center cooling plant
This is the development branch for a data center cooling plant model with `n` chillers and one optional water-side economizer.

The development branch is `issue735_dataCenter_chillerWSE`

### PR DESCRIPTION
**Pull request by mwetter**
This closes #735

### CODE REVIEW

**Comment by mwetter** [comment]
@YangyangFu : Can you please address the following before I proceed with further review and revisions:
- [ ] The package `Buildings.ChillerWSE.Examples.BaseClasses.Controls.Examples` requires an `info` section
- [ ] All 5 models in `Buildings.ChillerWSE.Examples.BaseClasses.Controls.Examples` require an `info` and `revision` section
- [ ] The model `Buildings.ChillerWSE.Validation.BaseClasses.PartialPlant` requires an `info` and `revision` section, and an icon.
- [ ] The partial model `Buildings.ChillerWSE.Examples.BaseClasses.DataCenter` requires an icon.
- [ ] The partial model `Buildings.ChillerWSE.Examples.BaseClasses.DataCenterControl` requires an icon.
- [ ] The file `ChillerWSE/Examples/BaseClasses/Controls/Examples.mo` needs to be stored as single files for each example.
- [ ] `Buildings.ChillerWSE.Examples.BaseClasses.Controls.CoolingTowerSpeedControl` fails to translate in the pedantic mode because `cooTowSpeCon` uses the conditionally removed variable `y_reset` outside of a `connect` statement (in a parameter assignment), which is illegal.

Note that I deleted
```
	deleted:    ChillerWSE/Examples/BaseClasses/Examples/ChillerStageControl.mo
	deleted:    ChillerWSE/Examples/BaseClasses/Examples/ConstantSpeedPumpStageControl.mo
	deleted:    ChillerWSE/Examples/BaseClasses/Examples/CoolingModeControl.mo
	deleted:    ChillerWSE/Examples/BaseClasses/Examples/CoolingTowerSpeedControl.mo
	deleted:    ChillerWSE/Examples/BaseClasses/Examples/VariableSpeedPumpStageControl.mo
	deleted:    ChillerWSE/Examples/BaseClasses/Examples/package.order
```
This package had no file `package.mo` and hence did not show up in Dymola. I believe you saved all its contents in `ChillerWSE/Examples/BaseClasses/Controls/Examples.mo`

Please make a new checkout from this branch so that you get all the recent changes.

**Comment by mwetter** [comment]
@YangyangFu : Please run the unit tests, and make sure the items at the above comment (https://github.com/lbl-srg/modelica-buildings/pull/869#issuecomment-324400931) are all addressed. For example, both
`../bin/runUnitTests.py --validate-html-only` and `../bin/runUnitTests.py --validate-experiment-setup` return errors. 

Furthermore, `NonIntegratedPrimarySecondary` does not translate in the pedantic mode of Dymola. The unit tests use the pedantic mode and hence this should be seen when you run the tests. You can run all unit tests in your new files using `../bin/runUnitTests.py -s Buildings.ChillerWSE`. Running these tests gives me the following output:
```
Generated 17 regression tests.

Number of models that failed check                           : 9
Number of models that failed to simulate                     : 9
Number of models with missing StateGraphRoot                 : 1

Script that runs unit tests had 1 warnings and 19 errors.
```
The file `unitTests.log` shows which models failed.


It is best if you make a new checkout from `lbl-srg:issue735_dataCenter_chillerWSE` to make sure you are working with the correct code.

When done, please make a new pull request against this branch.

**Comment by mwetter** [comment]
- [ ] `Examples.IntegratedPrimaryLoadSide` has a maximum room temperature of 60 degree Celsius. This need to be fixed and all examples checked to ensure that they meet the controls intent.
- [ ] `Examples/NonIntegratedPrimarySecondary` has a set point for supply air of 16 degree, but the supply air temperature becomes 36 degrees.
- [ ] `Buildings.ChillerWSE.BaseClasses.PartialPumpParallel` misses an `info` section.
- [ ] `Buildings.ChillerWSE.BaseClasses.PartialPumpParallel` has a shutoff valve that has no hysteresis. This can lead to chattering. Better would be to use the pump that uses m_flow as an input.

**Comment by YangyangFu** [comment]
@mwetter Hi Dr. Wetter, could you please open a branch so that I can pull the update results against it? The new branch should aim to solve the control errors in `Examples.IntegratedPrimaryLoadSide` , `Examples.NonIntegratedPrimarySecondary` and other examples.

**Comment by mwetter** [comment]
@YangyangFu : please use `issue914_controlErrorDataCenter`

**Pull request merged**
