### PR TITLE
Maint 10.0.x issue3697 translation fail om

### LINKED ISSUE #3697: DHC.Loads.Combined.Examples.BuildingTimeSeriesWithETS do not comply with Modelica Language Definition
The model `Buildings.Experimental.DHC.Loads.Combined.Examples.BuildingTimeSeriesWithETS` fails to compile with the latest nightly build of OpenModelica as it violates the Modelica standard. The cause is that `datDes.mCon_flow_nominal` has no binding, and there should also be an inner declaration for `datDes`.
The message is
```
[2] 11:10:43 Translation Warning
[Buildings.Experimental.DHC.Loads.Combined.BaseClasses.PartialBuildingWithETS: 8:3-9:75]: [An inner declaration for outer component datDes could not be found and was automatically generated.](omeditmessagesbrowser:///Buildings.Experimental.DHC.Loads.Combined.BaseClasses.PartialBuildingWithETS?lineNumber=8)

[3] 11:10:43 Translation Error
[Buildings.Experimental.DHC.Examples.Combined.BaseClasses.DesignDataSeries: 11:3-12:53]: [Parameter datDes.mCon_flow_nominal has neither value nor start value, and is fixed during initialization (fixed=true).](omeditmessagesbrowser:///Buildings.Experimental.DHC.Examples.Combined.BaseClasses.DesignDataSeries?lineNumber=11)
```

The same applies to `Buildings.Experimental.DHC.Loads.Combined.Examples.BuildingTimeSeriesWithETSDHWTank`.

This should be corrected on the master and on `maint_10.0.x`.

(If the library release notes are updated on 10.0.x, they don't need to be updated for 11.)

### PR DESCRIPTION
**Pull request by dhblum**
This is for #3697 and partner of https://github.com/lbl-srg/modelica-buildings/pull/3708.

This closes #3697

### CODE REVIEW

**Comment by dhblum** [comment]
@mwetter This is ready for your review and merge if tests pass.

**Review by mwetter — APPROVED** [review]

**Comment by mwetter** [comment]
@dhblum : This PR fails the CI tests: https://app.travis-ci.com/github/lbl-srg/modelica-buildings/jobs/619748332#L440

**Comment by dhblum** [comment]
I can't reproduce the CI failure, which is in Dymola.  The unit test for ``Buildings.Experimental.DHC.EnergyTransferStations.Cooling.Examples.Indirect`` passes locally using Dymola 2024x on Ubuntu 20.

The initialization failure for ``Buildings.Experimental.DHC.EnergyTransferStations.Cooling.Examples.Indirect`` on OM is known, it is listed on conf.yml.

**Comment by mwetter** [comment]
`Buildings.Experimental.DHC.EnergyTransferStations.Cooling.Examples.Indirect` also passes for me locally. I restarted this test on travis.

**Pull request merged**
