### PR TITLE
Issue2171 steady state sensors

### LINKED ISSUE #2171: Configure sensor models for extensive quantities in steady-state by default
See https://github.com/ibpsa/modelica-ibpsa/issues/1406

### PR DESCRIPTION
**Pull request by AntoineGautier**
This closes #2171.
A draft PR is created to document the impact on the simulation time. 
The changes will be documented and merged once the team approves that the impact is admissible.

### CODE REVIEW

**Comment by AntoineGautier** [comment]
The table below shows the impact on the simulation time for all the models within MBL that use one of the modified sensor models (as returned by OpenModelica function `getUsedClassNames`). 
The models with a significant simulation time AND an increased simulation time are `Buildings.Examples.DualFanDualDuct.ClosedLoop` and `Buildings.Examples.VAVReheat.ASHRAE2006`. They both use the volume flow rate sensor within a control loop. For `Buildings.Examples.DualFanDualDuct.ClosedLoop` the translation statistics are:

`master`

```
Continuous time states: 244 scalars
Time-varying variables: 4116 scalars
Alias variables: 8244 scalars
Number of mixed real/discrete systems of equations: 0
Sizes of linear systems of equations: {3, 5, 2, 2, 21, 6, 2, 2, 21, 6, 21, 6, 17, 21, 6, 2, 2, 17, 3, 3, 3, 16, 17, 17, 2, 2}
Sizes after manipulation of the linear systems: {0, 0, 0, 0, 10, 0, 0, 0, 10, 0, 10, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0}
Sizes of nonlinear systems of equations: {3, 1, 3, 3, 13, 3, 3, 1, 3, 3, 3, 3, 1, 5, 1, 1}
Sizes after manipulation of the nonlinear systems: {1, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0}
```

`issue2171_steadyStateSensors`
```
Continuous time states: 243 scalars
Time-varying variables: 4113 scalars
Alias variables: 8244 scalars
Number of mixed real/discrete systems of equations: 0
Sizes of linear systems of equations: {3, 5, 2, 2, 21, 6, 2, 2, 21, 6, 21, 6, 17, 21, 6, 2, 2, 17, 3, 3, 3, 16, 17, 17, 2, 2}
Sizes after manipulation of the linear systems: {0, 0, 0, 0, 10, 0, 0, 0, 10, 0, 10, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0}
Sizes of nonlinear systems of equations: {3, 1, 3, 3, 13, 3, 3, 1, 3, 3, 3, 3, 1, 5, 1, 1}
Sizes after manipulation of the nonlinear systems: {1, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0}
```
So the modification removes a state variable without any impact on the size of the systems of equations.
Despite that in some cases this leads to an increased number of Jacobian evaluations during the simulation, the simulation time is only marginally impacted (and within the tolerance of this performance benchmark based on single simulation runs).
Also note that for other models using also the volume flow rate sensor within a control loop (such as `Buildings.Examples.ScalableBenchmarks.BuildingVAV.Examples.OneFloor_OneZone` or `Buildings.Examples.ScalableBenchmarks.BuildingVAV.Examples.TwoFloor_TwoZone`) the modification decreases both the number of Jacobian evaluations and the simulation time.

|      | Model                                                                             |   master-Elapsed time (s) |   master-State events |   master-Jacobians |   issue2171_steadyStateSensors-Elapsed time (s) |   issue2171_steadyStateSensors-State events |   issue2171_steadyStateSensors-Jacobians |   (t2-t1)⁄t1 |
|-----:|:----------------------------------------------------------------------------------|--------------------------:|----------------------:|-------------------:|------------------------------------------------:|--------------------------------------------:|-----------------------------------------:|-------------:|
|  926 | Buildings.Fluid.Storage.Examples.StratifiedEnhancedInternalHex                    |                    0.157  |                     0 |                  5 |                                          0.1689 |                                           0 |                                        5 |         0.08 |
|  648 | Buildings.Fluid.Sensors.Conversions.Examples.To_VolumeFraction                    |                    0.0109 |                     0 |                 14 |                                          0.0118 |                                           0 |                                       13 |         0.07 |
|  393 | Buildings.Examples.DualFanDualDuct.ClosedLoop                                     |                   27.8167 |                    15 |                971 |                                         29.5989 |                                          15 |                                     1201 |         0.06 |
|  982 | Buildings.Examples.VAVReheat.ASHRAE2006                                           |                   28.5484 |                     7 |               1520 |                                         30.2655 |                                           7 |                                     1520 |         0.06 |
|  482 | Buildings.Fluid.Storage.Validation.HeatExchangerDynamics                          |                    0.3225 |                     1 |                 28 |                                          0.3421 |                                           1 |                                       28 |         0.06 |
|  356 | Buildings.Fluid.Chillers.Validation.Carnot_TEva_2ndLaw                            |                    0.0104 |                     0 |                  1 |                                          0.0106 |                                           0 |                                        1 |         0.02 |
|   43 | Buildings.Fluid.HeatExchangers.BaseClasses.Examples.HexElementLatent              |                    0.0157 |                     0 |                 56 |                                          0.0157 |                                           0 |                                       56 |         0    |
|  206 | Buildings.Fluid.Sensors.Examples.VolumeFlowRate                                   |                    0.0062 |                     0 |                  1 |                                          0.0063 |                                           0 |                                        1 |         0    |
|  805 | Buildings.Fluid.MixingVolumes.Examples.MixingVolumeMoistAir                       |                    0.0143 |                     0 |                 34 |                                          0.0141 |                                           0 |                                       34 |        -0.01 |
|  363 | Buildings.Fluid.MixingVolumes.Validation.MoistureMixingConservationSteadyState    |                    0.0066 |                     0 |                 18 |                                          0.0066 |                                           0 |                                       18 |        -0.01 |
|   95 | Buildings.Examples.VAVReheat.Validation.Guideline36SteadyState                    |                   96.9547 |                     1 |               6055 |                                         95.7751 |                                           1 |                                     6054 |        -0.01 |
|  521 | Buildings.Fluid.SolarCollectors.Examples.FlatPlateWithTank                        |                    0.123  |                     0 |                192 |                                          0.121  |                                           0 |                                      192 |        -0.02 |
|  245 | Buildings.Examples.ScalableBenchmarks.BuildingVAV.Examples.OneFloor_OneZone       |                    6.1825 |                   101 |                569 |                                          6.0423 |                                         101 |                                      554 |        -0.02 |
|   97 | Buildings.Examples.ScalableBenchmarks.BuildingVAV.Examples.TwoFloor_TwoZone       |                   31.1137 |                   258 |                856 |                                         29.5608 |                                         258 |                                      824 |        -0.05 |
| 1133 | Buildings.Examples.VAVReheat.Guideline36                                          |                   64.0049 |                   227 |               2717 |                                         60.705  |                                         227 |                                     2676 |        -0.05 |
|  187 | Buildings.Fluid.Storage.Validation.StratifiedNonUniformInitial                    |                    0.0137 |                     0 |                  4 |                                          0.0127 |                                           0 |                                        2 |        -0.07 |
|  360 | Buildings.Fluid.Actuators.Valves.Examples.TwoWayValveTable                        |                    0.0074 |                     0 |                  1 |                                          0.0067 |                                           0 |                                        1 |        -0.09 |
|  944 | Buildings.Fluid.Sensors.Examples.EnthalpyFlowRate                                 |                    0.008  |                     0 |                  7 |                                          0.0064 |                                           0 |                                        7 |        -0.2  |
|  354 | Buildings.Fluid.Sensors.Examples.MoistAirEnthalpyFlowRate                         |                    0.0084 |                     0 |                  4 |                                          0.0066 |                                           0 |                                        8 |        -0.21 |
|  335 | Buildings.Fluid.Storage.Validation.HeatExchangerLocation                          |                    0.0552 |                     0 |                 11 |                                          0.0431 |                                           0 |                                       11 |        -0.22 |
|  629 | Buildings.Fluid.Storage.Validation.StratifiedLoadingUnloading                     |                    0.0288 |                     1 |                 18 |                                          0.0223 |                                           1 |                                       15 |        -0.23 |
|  777 | Buildings.Fluid.Storage.Examples.Stratified                                       |                    0.0259 |                     0 |                  7 |                                          0.02   |                                           0 |                                        6 |        -0.23 |
| 1105 | Buildings.Fluid.MixingVolumes.Validation.MoistureMixingConservationDynamicBalance |                    0.0077 |                     0 |                 32 |                                          0.0056 |                                           0 |                                       32 |        -0.28 |
|  328 | Buildings.Fluid.FixedResistances.Validation.PlugFlowPipes.PlugFlowULg             |                    0.0435 |                     0 |                182 |                                          0.0281 |                                           0 |                                      181 |        -0.35 |
|  808 | Buildings.Fluid.MixingVolumes.Validation.MixingVolume                             |                    0.0148 |                     0 |                 85 |                                          0.0094 |                                           0 |                                       85 |        -0.37 |

**Comment by mwetter** [comment]
@AntoineGautier : Is there anything that remains to be done; or can we recommend to merge on the IBPSA library a (new) pull request https://github.com/ibpsa/modelica-ibpsa/compare/master...issue1406_steadyStateSensors to the master, and merge this on Buildings as well (once the tests pass)?
We have an IBPSA WP 1.1 coordination call this Friday on which we could discuss this and possibly wrap up.

**Comment by AntoineGautier** [comment]
@mwetter There was a simulation issue with the changes on the IBPSA library. I will look into that tomorrow again and update you on the call this Friday.

**Comment by mwetter** [comment]
@AntoineGautier : Thanks, I put it on the agenda for Friday.

**Comment by mwetter** [comment]
@AntoineGautier : I think this can be deleted as `tau` is set to `0` for these sensors due to the merge with the upstream IBPSA library.

**Comment by AntoineGautier** [comment]
This was addressed through #2323.

**Pull request closed without merging**
