### PR TITLE
Fixed undeclared parameters

### LINKED ISSUE #2555: Missing parameter prefixes in ThermalZones.Detailed
The following components are used as parameters but are not declared as such:
https://github.com/lbl-srg/modelica-buildings/blob/dd3df91c9bf47c13721c6f529f6f15e1fe9c703e/Buildings/ThermalZones/Detailed/Validation/BESTEST/Cases6xx/Case600FF.mo#L151-L155

https://github.com/lbl-srg/modelica-buildings/blob/dd3df91c9bf47c13721c6f529f6f15e1fe9c703e/Buildings/ThermalZones/Detailed/FLEXLAB/Rooms/X3B/Electrical.mo#L28-L31

### PR DESCRIPTION
**Pull request by JayHuLBL**
This closes #2555, #2556.

### CODE REVIEW

**Comment by casella** [comment]
@JayHuLBL, @mwetter, as @perost pointed out, this issue causes some failures when compiling Buildings 7.0.x with OMC, which we have a contractual obligation to fix by the end of 2021.

Could you please port this fix to the [7.0.x maintenance branch](https://github.com/lbl-srg/modelica-buildings/tree/maint_7.0.x), so we can have an up-to-date assessment on [our reports](https://libraries.openmodelica.org/branches/master/Buildings_7.0.0/Buildings_7.0.0.html)?

@sjoelund, from the [report](https://libraries.openmodelica.org/branches/master/Buildings_7.0.0/Buildings_7.0.0.html) I see we are testing b09ef282f, which is the [7.0.1 release](https://github.com/lbl-srg/modelica-buildings/releases/tag/v7.0.1). I don't get why the report says: `"provides": ["7.0.0"]` (just to add a bit more confusion? LOL), but that is another story. 

The question is: do we need LBL to issue a new 7.0.2 release with the latest fixes, or could we just track the [maint_7.0.x/HEAD](https://github.com/lbl-srg/modelica-buildings/tree/maint_7.0.x) version in the 7.0.0 report, so that it gets continuously updated with the latest fixes?

Thanks!

**Comment by perost** [comment]
> Could you please port this fix to the [7.0.x maintenance branch](https://github.com/lbl-srg/modelica-buildings/tree/maint_7.0.x), so we can have an up-to-date assessment on [our reports](https://libraries.openmodelica.org/branches/master/Buildings_7.0.0/Buildings_7.0.0.html)?

It's already ported to the maint_7.0.x branch, but since we test the 7.0.1 release we don't yet pick up the fixes in our testing.

**Comment by mwetter** [comment]
Please test against the HEAD of the `maint_7.0.x` branch. This way, fixes will propagate through to the OpenModelica test suite right away. Once we have full coverage, it would be good to make a release and also test against that branch.

Our most up to date branches are `master`, `maint_7.0.x` and `maint_8.0.x`.

**Comment by casella** [comment]
Sorry, I got confused by the commit and could not recognize them properly.

@sjoelund, @adrpo, can you please set up the Jenkins script so that it tests HEAD of the maintenance branch?

**Pull request merged**
