### PR TITLE
Issue2204 2201 loads time series

### PR DESCRIPTION
**Pull request by AntoineGautier**
Opening the PR to trigger CI testing.

### CODE REVIEW

**Comment by AntoineGautier** [comment]
@Helarga Can you please solve the CI test errors and let me know when you do so? I will pull the branch from your fork directly. 
When the tests pass, this is ready to merge (the development was reviewed in #2269 and this branch addresses the last comments from https://github.com/lbl-srg/modelica-buildings/pull/2269#issuecomment-741963606).

**Comment by Helarga** [comment]
@AntoineGautier, please pull it now .

Regarding the addressing  of the comments of  #2269, I haven't fixed the new bug that you found yesterday at your model of the partial terminal unit. I mean that the time series model currently on the MBL master branch has this new discovered bug.

**Comment by AntoineGautier** [comment]
@Helarga The bug has only some effect if a scaling factor different than 1 is used together with a model that uses time series to provide loads. From https://github.com/lbl-srg/modelica-buildings/pull/2269#issuecomment-742005103 and https://github.com/lbl-srg/modelica-buildings/pull/2269#issuecomment-742005424 there is no such case currently on `issue2204_gmt_mbl`. The bug will be fixed in https://github.com/lbl-srg/modelica-buildings/issues/2302.

**Comment by Helarga** [comment]
i was checking actually the <code> have_scaLoa = false/true </code> at the model here on the mbl master branch "the original model"
Buildings.Experimental.DHC.Loads.Examples.CouplingTimeSeries
 this is in case of true
image

this is in case of false 
image

exactly the same results.
 yes i agree the time series model needs corrections.

**Pull request merged**
