### PR TITLE
Issue1502 new add of replaceable thermal zone models

### LINKED ISSUE #1502: Implement a thermal zone model as a replaceable class

### PR DESCRIPTION
**Pull request by milicag**
This PR deprecates PR [#1663](https://github.com/lbl-srg/modelica-buildings/pull/1663) and therefore closes #1502.

### CODE REVIEW

**Review by milicag — COMMENTED** [review]
@milicag

**Comment by AntoineGautier** [comment]
@milicag The example models in `ThermalZones.EnergyPlus.Examples.VAVReheatRefBldgSmallOffice` do not pass OCT check due to the following error. I proposed a fix in https://github.com/lbl-srg/modelica-buildings/pull/2189/commits/f2aa55e593b070be5186a14400860be0ca359009.

```
Error at line 86, column 10, in file '/home/agautier/gitrepo/modelica-buildings/Buildings/ThermalZones/EnergyPlus/Examples/VAVReheatRefBldgSmallOffice/BaseClasses/Floor.mo':
  Equality comparisons do not allow real operands: abs(opeWesCor.wOpe - 4) == 0.0
    type of 'abs(opeWesCor.wOpe - 4)' is Real
    type of '0.0' is Real
```

**Comment by AntoineGautier** [comment]
Comparison with the VAVReheat models on the master branch, based on annual simulations with OCT.

```
branch=master
commit=010ac56de3770548a1e829de1275612f34c2afc4

.. table:: Heating, cooling, fan and total site HVAC energy, and savings of guideline 36 case versus base case.

   ===================================== ===================================== ====================================== ====================================== =====
   :math:`E_{h} \quad [kWh/(m^2\,a)]`    :math:`E_{c} \quad [kWh/(m^2\,a)]`    :math:`E_{f} \quad [kWh/(m^2\,a)]`     :math:`E_{tot} \quad [kWh/(m^2\,a)]`     [%]
   ===================================== ===================================== ====================================== ====================================== =====
                                    5.08                                 16.07                                  2.365                                  23.51   
                                   3.667                                 14.71                                   1.83                                  20.21  14.1 
   ===================================== ===================================== ====================================== ====================================== =====
  
  
CPUtime, annual_base 72'
CPUtime, annual_g36 145'
```

**Comment by mwetter** [comment]
@milicag : Is it intentionally that the thermal zones in `Buildings.ThermalZones.EnergyPlus.Examples.VAVReheatRefBldgSmallOffice` compute the internal loads twice, once from the idf file, and once from the Modelica input? If not, please set it to zero in the Modelica model and make sure that the heating and cooling capacity is still meaningful.

**Comment by mwetter** [comment]
Todo
- [ ] Verify system size as the internal gains are now lower.

**Review by mwetter — APPROVED** [review]
Ready to merge when all tests pass.

**Pull request merged**
