### PR TITLE
Issue761 cdl mode selection

### PR DESCRIPTION
**Pull request by JayHuLBL**
block to specify system operation mode.

### CODE REVIEW

**Comment by mwetter** [comment]
@JayHuLBL 

I revised some of the model and committed my changes to this branch.

Could you please do the following in `OperationModeSelection`:

- [ ] add comment to all instances (in the future, we want to tighten our tests to make sure everything is commented
- [ ] Reorder so that all parameters are first (which is the case already), then all inputs are listed, then all outputs, and afterwards all instances. This order should be for the public declarations first, and then for all protected declarations. This way, inputs and outputs show up on top in the result browser.
- [ ] Update figures as I renamed `TZon`, `TUnoHeaSet` and `TUnoCooSet`
- [ ] What does "...occupied start hour..." mean? I don't see, and I don't think we should, restrict
  the start to a full hour. Hence, "...occupied start time..." would be clearer.
- [ ] All inputs (or outputs if present) that have units, such as `TUnoCooSet`, should be declared
   like
   ```
    ... TUnoCooSet(
          final unit="K",
          quantity="ThermodynamicTemperature") ...
   ```

- [ ] The section
   ```
  parameter Integer occModRan = 1 "Occupied mode index";
  parameter Integer cooDowRan = 2 "Cool-down mode index";
  parameter Integer setUpRan =  3 "Set-up mode index";
  parameter Integer warUpRan =  4 "Warm-up mode index";
  parameter Integer setBacRan = 5 "Set-back mode index";
  parameter Integer freProRan = 6 "Freeze protection mode index";
  parameter Integer unoModRan = 7 "Unoccupied mode index";
   ```
   are values that are needed in many models for Guideline 36. Hence, they should be moved to 
   `ASHRAE.G36.Constants.OperationModes`
- [ ] Rename `OperationModeSelection` to `OperationModeSelector` and use a shorter name in
  the validation example.
- [ ] Ensure that the merged `package.mo` files all have an info section that briefly describes the package.

**Comment by JayHuLBL** [comment]
Following updates have been finished:
- [x] add comment to all instances
- [x] reorder contents so to have following orders: parameters, inputs, outputs, instances.
- [x] updated figures
- [x] change "occupied start hour" to "occupied start time"
- [x] declare inputs
- [x] create `OpenBuildingControl.ASHRAE.G36.Constants` package so that move operation modes indices to `OpenBuildingControl.ASHRAE.G36.Constants.OperationModes`
- [x] rename `OperationModeSelection` to `OperationModeSelector`
- [x] add package information documentation

**Comment by JayHuLBL** [comment]
@mwetter The model would be ready for review if Travis test is successful.

**Comment by JayHuLBL** [comment]
@mwetter The pull request is ready for review.

**Comment by mwetter** [comment]
@JayHuLBL 
- [ ] This pull request deletes `VAVSingleZoneTSupSet` including its implementation, validation, figures etc. I think this is by mistake as I don't see how it is being replaced. Can you please correct this.

**Comment by mwetter** [comment]
Merged through https://github.com/lbl-srg/modelica-buildings/pull/837

**Pull request merged**
