### PR TITLE
Make BCVTB header file C89 compliant.

### PR DESCRIPTION
**Pull request by tsnouidui**
@mwetter: This addresses issue #569.

### CODE REVIEW

**Comment by mwetter** [comment]
@tsnouidui 
Please also update the other files in `Buildings/Resources/C-Sources`

**Comment by tsnouidui** [comment]
@mwetter. I made the changes in C-Sources and did a ` grep -r ///` on the `Buildings.Resources` folder. I found out that the entire source code of `FastFluidDynamics` uses such constructs in various places. 
I will assign this to the original developers. 

@tianwei1989 @zuowangda . The JModelica compiler requires comments in C-sources and C-header files to be C-89 compliant. Could you please replace `///` in the comment section with /* */ as it is currently done in `Buildings.Resources.Include.bcvtb.h`? This affects various files in `Buildings.Resources.src.FastFluidDynamics`. You can then commit the changes on this branch.

Thanks!

**Comment by tianwei1989** [comment]
@tsnouidui @zuowangda @mwetter I will work on the revision of comments format for FFD source codes. I will create a pull request after I complete the task. Thanks,
Wei Tian

**Comment by tsnouidui** [comment]
@tianwei1989 @mwetter @zuowangda I suggest to get branch issue569_bcvtb (https://github.com/lbl-srg/modelica-buildings/tree/issue569_bcvtb) which was created for the C-89 compliances and push your changes on that branch.
Thanks!

**Comment by tianwei1989** [comment]
@tsnouidui Dr. Nouidui, I have cleared up the `///` in FFD source codes and a pull request is going to be sent. Please let me know if you have further problem regarding this issue. Thanks, Wei.

**Comment by tsnouidui** [comment]
@mwetter I merged Wei changes.

Thanks!

**Comment by mwetter** [comment]
@tsnouidui 
Can you please also correct all `*\param `, `*\return` etc These come originally from doxygen as `///\param` but are probably invalid now.

**Comment by tsnouidui** [comment]
@mwetter @tianwei1989 I will replace all` *\ `with `*@`.

**Comment by tsnouidui** [comment]
@mwetter I had to change a number of files and I am now able to compile the code with` -std=c89` flag. 
@tianwei1989 You can review my changes and see if there is anything suspicious.

**Comment by mwetter** [comment]
@tsnouidui I don't see the warnings anymore when I compile from JModelica.

**Comment by tsnouidui** [comment]
@mwetter This can then be merged and closed I guess.

**Pull request merged**
