### PR TITLE
Issue1151 plots

### LINKED ISSUE #1151: add blocks that plot time series and x-y plots
This is to add blocks that plot x-y plots and time series, and write these plots to an html file.

### PR DESCRIPTION
**Pull request by mwetter**
This closes #1151.
It adds a package for generating scatter plots and time series plots.

### CODE REVIEW

**Comment by mwetter** [comment]
@milicag : Can you please review these new plotting capability. This can be used for the control verification to create either time series plots or scatter plots. See the various examples.

**Comment by mwetter** [comment]
- [ ] The plot in the documentation needs be updated after https://github.com/lbl-srg/modelica-buildings/pull/1154 is merged.

**Comment by milicag** [comment]
@mwetter It would be convenient for me to have the master merged into this for the validation example (it needs both plotters and the csv writter).

**Comment by mwetter** [comment]
@milicag I just merged the master.

**Pull request merged**
