### PR TITLE
Issue1502 replaceable thermal zone staging

### PR DESCRIPTION
**Pull request by AntoineGautier**
@kuzha @JayHuLBL This is our staging branch for the updates we just discussed.
It was created with
```
git checkout issue1502_replaceable_thermal_zone
git pull origin master
```
I opened a draft PR (against `issue1502_replaceable_thermal_zone`) to track the changes.

TODO:

- [x] @JayHuLBL Can you start with merging the mode selection refactoring?

### CODE REVIEW

**Comment by JayHuLBL** [comment]
@AntoineGautier @kuzha 
I have merged the refactored sequence of specifying operation mode. We can start refactor the `ASHRAE2006` and `Guideline36` now.

**Comment by AntoineGautier** [comment]
After merging `issue2028_dualMin` (which includes #2030) the comparison of the models in `Buildings.ThermalZones.EnergyPlus.Examples.VAVReheatRefBldgSmallOffice` gives the following.

**Branch `issue1502_replaceable_thermal_zone_staging`** (commit 47cb4b97e476bc39e01e666db63f883959045dea)
(tolerance 1e-6)

```
.. table:: Heating, cooling, fan and total site HVAC energy, and savings of guideline 36 case versus base case.

   ===================================== ===================================== ====================================== ====================================== =====
   :math:`E_{h} \quad [kWh/(m^2\,a)]`    :math:`E_{c} \quad [kWh/(m^2\,a)]`    :math:`E_{f} \quad [kWh/(m^2\,a)]`     :math:`E_{tot} \quad [kWh/(m^2\,a)]`     [%]
   ===================================== ===================================== ====================================== ====================================== =====
                                   9.352                                  13.0                                  1.678                                  24.03   
                                   7.838                                 10.68                                  1.144                                  19.66  18.2 
   ===================================== ===================================== ====================================== ====================================== =====
  
  
CPUtime, base 4'
CPUtime, G36  43'
```

**Branch `issue1502_replaceable_thermal_zone`** (commit f4ae812d558b8d0ccccb9cd2161c95ba33fabfa5)
(tolerance 1e-8)

```
.. table:: Heating, cooling, fan and total site HVAC energy, and savings of guideline 36 case versus base case.

   ===================================== ===================================== ====================================== ====================================== =====
   :math:`E_{h} \quad [kWh/(m^2\,a)]`    :math:`E_{c} \quad [kWh/(m^2\,a)]`    :math:`E_{f} \quad [kWh/(m^2\,a)]`     :math:`E_{tot} \quad [kWh/(m^2\,a)]`     [%]
   ===================================== ===================================== ====================================== ====================================== =====
                                    12.7                                 17.09                                  2.097                                  31.89   
                                   6.656                                  10.0                                 0.8256                                  17.49  45.2 
   ===================================== ===================================== ====================================== ====================================== =====
  
  
CPUtime, base 16'
CPUtime, G36  146'
```

**Comment by mwetter** [comment]
@AntoineGautier : The branch `issue1502_replaceable_thermal_zone` has been updated with the latest `master` and the latest `issue1129_energyPlus_zone`. Can you please update on `issue1502_replaceable_thermal_zone` the reference results

- Buildings_ThermalZones_EnergyPlus_Examples_VAVReheatRefBldgSmallOffice_Guideline36.txt,
- Buildings_ThermalZones_EnergyPlus_Examples_VAVReheatRefBldgSmallOffice_ASHRAE2006.txt,

which have different flow rates. I did not commit them to make sure you can verify whether these changes are fine.

Then please merge or close this PR based on the last item in https://github.com/lbl-srg/modelica-buildings/pull/2031#issuecomment-666156099

**Comment by AntoineGautier** [comment]
@mwetter The minimum discharge air flow set point in the instances of `Controls.OBC.ASHRAE.G36_PR1.TerminalUnits.Controller` has been changed to
`final VDisSetMin_flow=max(1.5*VCorOA_flow_nominal, 0.15*mCor_flow_nominal/1.2)`.
See https://github.com/lbl-srg/modelica-buildings/pull/2030#discussion_r452985141 for the rationale.
(I just wonder now if making this parameter `final` is the best option though.)
The same setting is used for ASHRAE2006 in the instances of `Examples.VAVReheat.Controls.RoomVAV` which ensures a fair comparison.
This explains the difference in the discharge air flow rate from the reference results.

**Comment by mwetter** [comment]
@AntoineGautier : I think it is better to make `VDisSetMin_flow` not final.

**Comment by AntoineGautier** [comment]
Closed now that #2031 is merged, according to https://github.com/lbl-srg/modelica-buildings/pull/2031#issuecomment-666156099

**Comment by AntoineGautier** [comment]
Closed now that #2031 is merged, according to https://github.com/lbl-srg/modelica-buildings/pull/2031#issuecomment-666156099

**Pull request closed without merging**
