### PR TITLE
Fix TrueFalseHold with unit impulse input signal

### PR DESCRIPTION
**Pull request by AntoineGautier**
This addresses #3966.

### CODE REVIEW

**Comment by AntoineGautier** [comment]
## Unit tests failing

### `Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice`

This is due to the following sequence within `Buildings.Controls.OBC.ASHRAE.G36.ZoneGroups.OperationMode`.

image

The following plot compares the results between the master branch `//1` and the feature branch `//2`.

image

We can verify that the feature branch yields the expected results.

**Comment by AntoineGautier** [comment]
There is still an issue with the implementation in 72c45d3 that is visible in the plots for `Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice` in https://github.com/lbl-srg/modelica-buildings/pull/3967#issuecomment-2310093495.
The condition `time >= pre(entryTimeFalse) + falseHoldDuration and time >= pre(entryTimeTrue) + trueHoldDuration` does not fire the when clause as expected based on https://specification.modelica.org/maint/3.6/equations.html#when-equations:

> The equations within a when-equation are activated only at the instant when the scalar expression or any of the elements of the vector expression becomes true.

This seems related to the CVODE solver. The plot below compares the trajectories of the same variables between DASSL (diagram 1) and CVODE (diagram 2).

image

As a workaround for CVODE, the vector expression is split into two separate when clauses.

**Comment by AntoineGautier** [comment]
@JayHuLBL This is ready for your review. 
(Another PR more complicated than anticipated: 2 tickets open at DS, 1 at Modelon)

**Review by JayHuLBL — APPROVED** [review]
@AntoineGautier It looks good. Thanks for the fix.

**Comment by AntoineGautier** [comment]
@mwetter This is ready to merge.

**Review by mwetter — APPROVED** [review]

**Comment by mwetter** [comment]
Thanks, that was indeed a hard one...

**Pull request merged**
