### PR TITLE
Rename DHC models and update release notes

### PR DESCRIPTION
**Pull request by EttoreZ**
This PR addresses issues #3694 and #3712.

### CODE REVIEW

**Review by mwetter — CHANGES_REQUESTED** [review]
@EttoreZ 
This PR has files with broken links that need to be corrected. See below. To reproduce and check, export the HTML description.
Note that there are also broken links in the Aquifer package, but I will handle them separately.
```
Warning: Can not resolve link "modelica://Buildings.Experimental.DHC.EnergyTransferStations.Combined.Subsystems.HeatPump_Old" in Buildings.Experimental.DHC.EnergyTransferStations.Combined.HeatPumpHeatExchanger
Warning: Can not resolve link "modelica://Buildings.Experimental.DHC.EnergyTransferStations.Combined.HeatPumpHeatExchanger_Current" in Buildings.Experimental.DHC.EnergyTransferStations.Combined.Subsystems.SwitchBox
Warning: Can not resolve link "modelica://Buildings.Experimental.DHC.EnergyTransferStations.Combined.Subsystems.HeatPump_Old" in Buildings.Experimental.DHC.EnergyTransferStations.Combined.Subsystems.Validation.HeatPump
Warning: Can not resolve link "modelica://Buildings.Experimental.DHC.EnergyTransferStations.Combined.HeatPumpHeatExchanger_Current" in Buildings.Experimental.DHC.Loads.Combined.BaseClasses.PartialBuildingWithETS
Warning: Can not resolve link "modelica://Buildings.Experimental.DHC.Networks.Combined.BaseClasses" in Buildings.Experimental.DHC.Networks.Pipes.Validation
```

**Comment by dhblum** [comment]
@mwetter I'm noticing your comment on broken links.  When I for example have ``Buildings.Experimental.DHC.EnergyTransferStations.Combined`` highlighted in my package browser and use Tools>HTML to export html with Type=Modelica documentation, I don't see those warnings and errors in any log output in the Dymola window (though if I navigate to the links, I see they are not correct as your warnings indicate.  I'm confirming this is Dymola 2024x.  What am I missing?

**Comment by mwetter** [comment]
Try to export it for Buildings.Experimental. I exported it for Buildings,
but this will take around half an hour.

**Comment by dhblum** [comment]
I just tried for Buildings.Experimental and still don't see any warnings/errors, though when I open the html files, indeed one of the links in your warnings output is broken.

**Comment by dhblum** [comment]
Ohh, ok I see the warnings in the Commands tab, not the Logs tab!

**Comment by dhblum** [comment]
@EttoreZ I'll take care of fixing the links since I have it open now.

**Comment by dhblum** [comment]
> @EttoreZ This PR has files with broken links that need to be corrected. See below. To reproduce and check, export the HTML description. Note that there are also broken links in the Aquifer package, but I will handle them separately.
> 
> ```
> Warning: Can not resolve link "modelica://Buildings.Experimental.DHC.EnergyTransferStations.Combined.Subsystems.HeatPump_Old" in Buildings.Experimental.DHC.EnergyTransferStations.Combined.HeatPumpHeatExchanger
> Warning: Can not resolve link "modelica://Buildings.Experimental.DHC.EnergyTransferStations.Combined.HeatPumpHeatExchanger_Current" in Buildings.Experimental.DHC.EnergyTransferStations.Combined.Subsystems.SwitchBox
> Warning: Can not resolve link "modelica://Buildings.Experimental.DHC.EnergyTransferStations.Combined.Subsystems.HeatPump_Old" in Buildings.Experimental.DHC.EnergyTransferStations.Combined.Subsystems.Validation.HeatPump
> Warning: Can not resolve link "modelica://Buildings.Experimental.DHC.EnergyTransferStations.Combined.HeatPumpHeatExchanger_Current" in Buildings.Experimental.DHC.Loads.Combined.BaseClasses.PartialBuildingWithETS
> Warning: Can not resolve link "modelica://Buildings.Experimental.DHC.Networks.Combined.BaseClasses" in Buildings.Experimental.DHC.Networks.Pipes.Validation
> ```

@EttoreZ @mwetter These are corrected in https://github.com/lbl-srg/modelica-buildings/pull/3719/commits/d6c477933269bb276b247c13122e769f9d5b98db.

**Comment by EttoreZ** [comment]
Thank you @dhblum. I merged the latest version of master and the PR should be ready to merge once it passes the tests

**Comment by dhblum** [comment]
@mwetter Just letting you know you set this to automerge yesterday but it hasn't merged because your review technically hasn't been approved in github.

**Review by mwetter — APPROVED** [review]

**Pull request merged**
