### PR TITLE
Issue1463 steam absorption chiller

### PR DESCRIPTION
**Pull request by Helarga**

### CODE REVIEW

**Comment by mwetter** [comment]
@Helarga Before I merge it can you please test
```
cd Resources/Data/Fluid/Chillers/IndirectAbsorptionChiller
./run_IndirectAbsorptionChiller.sh
```
This fails with 
```
File IndirectAbsorptionChiller.csv does not exist: 'IndirectAbsorptionChiller.csv'
```
If I copy manually the csv file from EnergyPlus and run your script, then I get diffs on `modelica.csv`

**Comment by Helarga** [comment]
> @Helarga Before I merge it can you please test
> 
> ```
> cd Resources/Data/Fluid/Chillers/IndirectAbsorptionChiller
> ./run_IndirectAbsorptionChiller.sh
> ```
> 
> This fails with
> 
> ```
> File IndirectAbsorptionChiller.csv does not exist: 'IndirectAbsorptionChiller.csv'
> ```
>
> If I copy manually the csv file from EnergyPlus and run your script, then I get diffs on `modelica.csv`

**Comment by Helarga** [comment]
> @Helarga Before I merge it can you please test
> 
> ```
> cd Resources/Data/Fluid/Chillers/IndirectAbsorptionChiller
> ./run_IndirectAbsorptionChiller.sh
> ```
> 
> This fails with
> 
> ```
> File IndirectAbsorptionChiller.csv does not exist: 'IndirectAbsorptionChiller.csv'
> ``` 
>  
> If I copy manually the csv file from EnergyPlus and run your script, then I get diffs on `modelica.csv`

**Comment by Helarga** [comment]
> @mwetter 
> 
> ```
> cd Resources/Data/Fluid/Chillers/IndirectAbsorptionChiller
> ./run_IndirectAbsorptionChiller.sh
> ```
> 
> This fails with
> 
> ```
> File IndirectAbsorptionChiller.csv does not exist: 'IndirectAbsorptionChiller.csv'
> ```
> **I did the following
1-cd Resources/Data/Fluid/Chillers/IndirectAbsorptionChiller
2- Gave execute permission to the script:
chmod +x run_IndirectAbsorptionChiller.sh
 3- then 
 ./run_IndirectAbsorptionChiller.sh**



If I copy manually the csv file from EnergyPlus and run your script, then I get diffs on `modelica.csv`
**I fixed the diffs!**

**Pull request closed without merging**
