### PR TITLE
Issue 3727 Move DHC

### PR DESCRIPTION
**Pull request by dhblum**
This is for #3727.  It moves ``Buildings.Experimental.DHC`` to ``Buildings.DHC``.

@mwetter I generated html documentation for the whole Buildings Library after this move and saw no errors or warnings.

Also, shall ``Buildings.Experimental`` be removed?

### CODE REVIEW

**Comment by mwetter** [comment]
@dhblum : Yes, please remove `Buildings.Experimental` (and update package.order).

Also, there are still some stray files that need to be removed:
```bash
$ find . -name '*' | grep Experimental
./Resources/Data/Experimental
./Resources/Data/Experimental/DHC
./Resources/Data/Experimental/DHC/Loads
./Resources/Data/Experimental/DHC/Loads/BaseClasses
./Resources/Data/Experimental/DHC/Loads/BaseClasses/Validation
./Resources/Data/Experimental/DHC/Loads/BaseClasses/Validation/RefBldgLargeOfficeNew2004_7.1_5.0_3C_USA_CA_SAN_FRANCISCO.mos
./Resources/Data/Experimental/DHC/Loads/Examples
./Resources/Data/Experimental/DHC/Loads/Examples/MediumOffice-90.1-2010-5A.mos
./Resources/Data/Experimental/DHC/Loads/Examples/SwissHospital_20190916.mos
./Resources/Data/Experimental/DHC/Loads/Examples/SwissOffice_20190916.mos
./Resources/Data/Experimental/DHC/Loads/Examples/BaseClasses
./Resources/Data/Experimental/DHC/Loads/Examples/BaseClasses/GeojsonExportRC
./Resources/Data/Experimental/DHC/Loads/Examples/BaseClasses/GeojsonExportRC/OfficeBuilding
./Resources/Data/Experimental/DHC/Loads/Examples/BaseClasses/GeojsonExportRC/OfficeBuilding/InternalGains_Meeting.txt
./Resources/Data/Experimental/DHC/Loads/Examples/BaseClasses/GeojsonExportRC/OfficeBuilding/InternalGains_Floor.txt
./Resources/Data/Experimental/DHC/Loads/Examples/BaseClasses/GeojsonExportRC/OfficeBuilding/InternalGains_Storage.txt
./Resources/Data/Experimental/DHC/Loads/Examples/BaseClasses/GeojsonExportRC/OfficeBuilding/InternalGains_Office.txt
./Resources/Data/Experimental/DHC/Loads/Examples/BaseClasses/GeojsonExportRC/OfficeBuilding/InternalGains_ICT.txt
./Resources/Data/Experimental/DHC/Loads/Examples/BaseClasses/GeojsonExportRC/OfficeBuilding/InternalGains_Restroom.txt
./Resources/Data/Experimental/DHC/Loads/Examples/SwissResidential_20190916.mos
./Resources/Data/Experimental/DHC/Loads/Examples/.gitignore
./Resources/Data/Experimental/DHC/Loads/HotWater
./Resources/Data/Experimental/DHC/Loads/HotWater/DHW_ApartmentMidRise.mos
./Resources/ReferenceResults/Dymola/Buildings_Experimental_DHC_Networks_Combined_BaseClasses_Validation_Pipe.txt
./Resources/ReferenceResults/Dymola/Buildings_Experimental_DHC_Loads_HotWater_Examples_HeaterAndFixtureHeatPumpWithTank.txt
./Experimental
./Experimental/package.mo
./Experimental/package.order

```

**Comment by dhblum** [comment]
@mwetter Looking into those stray files you list, some are still needed.  For example, in ``Buildings.DHC.Examples.Combined.SeriesConstantFlow`` there is still the declaration:

```
  parameter String filNam[nBui]={
    "modelica://Buildings/Resources/Data/Experimental/DHC/Loads/Examples/SwissOffice_20190916.mos",
    "modelica://Buildings/Resources/Data/Experimental/DHC/Loads/Examples/SwissResidential_20190916.mos",
    "modelica://Buildings/Resources/Data/Experimental/DHC/Loads/Examples/SwissHospital_20190916.mos"}
    "Library paths of the files with thermal loads as time series";
```

So, it seems using only the move function from buildingspy is still incomplete, since those file references are not moved.  Just checking, is this correct?  If so then I need to more carefully go through which of those stray files are still needed, move them appropriately to a new directory, and update the declarations in the dependent models.

**Comment by mwetter** [comment]
@dhblum It looks like BuildingsPy is not going into the `Data` directory when it moves things around. Please move them manually.

**Comment by dhblum** [comment]
Ok will do.

**Comment by dhblum** [comment]
Closing, use https://github.com/lbl-srg/modelica-buildings/pull/3781 instead.

**Pull request closed without merging**
