### PR TITLE
Issue1858 update loads

### LINKED ISSUE #1858: Update base models for Loads
Models in `Buildings.Applications.DHC.Networks.BaseClasses` shall be updated.

- [x] Rename parameter `have_heaFloOut` as `show_Q`.
- [x] Keep a state in the temperature sensor model to avoid algebraic coupling.
- [x] Modify `mDis_flow_nominal` as the nominal mass flow rate in the distribution line before **the first** connection 
- [x] Compute `mEnd_flow_nominal` from `mDis_flow_nominal` and `mCon_flow_nominal`
- Package the computation of `Q_flow` from temperature measurements in a reusable block: this is moved to #1769.
- Double check that replaceable types cannot be propagated and document the redeclare logic: this is moved to #1769.

In `Buildings.Applications.DHC.Loads.Examples.CouplingTimeSeries`

- [x] Update `mLoaHea_flow_nominal` and `mLoaCoo_flow_nominal` to representative values for FCU and use the scaling factor to size for the design load.

In `Buildings.Applications.DHC.Loads.BaseClasses.PartialTerminalUnit`

- [x] Check if `MassFlowRateMultiplier` could not be useful on the load side as well, in case of large thermal zones covering several rooms.
- [x] Add `HeatFlowRateMultiplier` for heat ports.

In `Buildings.Applications.DHC.Controls.MixingValveControl`

- [x] Correct description string of `toBoo` in `Buildings.Applications.DHC.Controls.MixingValveControl`.

In `Buildings.Applications.DHC.Loads.BaseClasses.PartialBuilding`

- [x] Refactor with `ports_aHeaWat` and `ports_aChiWat`, both conditional.

In `Buildings.Applications.DHC.Loads.BaseClasses.PartialBuilding` 

- [x] Update schematic to include distributor / collector line in `PartialBuilding`
- [x] Check the image size (too big on standard dpi).

In `Buildings.Applications.DHC.Loads.Examples.BaseClasses.BuildingSpawnZ6`

- [x] Let the `Attic` zone unconditioned.

In `Buildings.Applications.DHC.Loads.Examples.CouplingTimeSeries` 

- [x] Check the mismatch between `QReqHea_flow` and `QActHea_flow`, see plot.
- [x] Add integrator of heat flow rate for validation in energy.

Buildings Applications DHC Loads Examples CouplingTimeSeries_plot

@amyeallen1 to review PR.

Updates to handle steam distribution will be addressed in a specific issue by @khinkelman.

### PR DESCRIPTION
**Pull request by AntoineGautier**
This closes #1858.
@amyeallen1 Could you please review this PR? 
Please also consider my comments in the issue regarding the mismatch you noticed.

### CODE REVIEW

**Comment by AntoineGautier** [comment]
@amyeallen1 I noticed an improper setting of nominal values for some parameters in validation models. When using a scaling factor for the terminal unit models, this lead to initialization errors or enhanced simulation time. This has been corrected with my last commits.

**Comment by AntoineGautier** [comment]
@amyeallen1 Is it OK to merge after our last discussions?

**Comment by amyeallen1** [comment]
Hi Antoine, sure, please go ahead. Thanks for checking. @AntoineGautier

**Comment by AntoineGautier** [comment]
@nllong Please note that this PR is non-backward compatible because

- the parameter `mDis_flow_nominal` in `Buildings.Applications.DHC.Networks.BaseClasses.PartialDistribution1Pipe` and `Buildings.Applications.DHC.Networks.BaseClasses.PartialDistribution2Pipe` is now a scalar (it used to be an array),
- the model `Buildings.Applications.DHC.Loads.BaseClasses.PartialBuilding` now has dedicated ports for heating and chilled water.

**Comment by nllong** [comment]
Thanks @AntoineGautier for the heads up. Our CI will fail and then I'll update based on what you listed as the changes. We should be ready for the PartialBuilding update.

**Pull request merged**
