### PR TITLE
Add new features to the AWHP plant template

### PR DESCRIPTION
**Pull request by AntoineGautier**
This addresses #3808.

With this PR:

1. Exhaustive testing of all template configurations is now exclusively carried out with Dymola. This change is necessary because some configurations of the HP plant template fail to simulate with OCT (tracked under #3759), and the current test workflow (`make test-templates-*` in `.travis.yml`) does not support excluding specific configurations for a given simulator. 
However, the main validation model is still tested with all tools (`make test-*  PACKAGE=\"Buildings.Templates\"`), which ensures that the templates are at least validated in their default configuration.
2. Only ***30 %*** of all supported configurations are tested — for HP plants, but also VAV systems. This is because a single Travis job cannot last more than 120 min (https://docs.travis-ci.com/user/customizing-the-build#build-timeouts), and setting `TRAVIS_WAIT=180` or higher does not extend this limit (see for example the result of a failed test from this PR: https://api.travis-ci.com/v3/job/622428039/log.txt).
    - To prepare for an increasing number of templates in the future, we should think about having a Travis test for each package under `Templates`, or switch to a more flexible CI tool like Gitlab on a local server.

### CODE REVIEW

**Comment by AntoineGautier** [comment]
This is ready for review.

**Comment by AntoineGautier** [comment]
@mwetter This is ready for review.

@karthikeyad-pnnl Consider checking out this branch for the development of other HP plant templates. It contains a few additions and corrections to the basic control blocks and components used to create the AWHP template currently in the master branch.

**Review by mwetter — CHANGES_REQUESTED** [review]
@AntoineGautier : Can you please also update the schematic drawing that is shown in the info section of Buildings.Templates.Plants.HeatPumps.AirToWater

**Comment by AntoineGautier** [comment]
@mwetter I've updated the schematics in 853181b. Please let me know if there are any other changes to consider. Otherwise, I'll trigger the CI tests and we can then merge this branch.

**Review by mwetter — APPROVED** [review]
@AntoineGautier : Thanks for the changes. This is ready to be merged.

**Pull request merged**
