### PR TITLE
Undo removal of latent heat transfer to compute the coil state in HexElementLatent - Maint 8.1.x

### PR DESCRIPTION
**Pull request by dhblum**
This is for https://github.com/lbl-srg/modelica-buildings/issues/3065, following https://github.com/lbl-srg/modelica-buildings/pull/3073, to update the Maintenance 8.1.x branch.

@mwetter, the udpated model and documentation files pushed here so far.  Have not updated reference results yet.  Two things:

1. I made the changes needed for using for MSL 3.2.3.  I then ran unit tests with buildingspy 2.2.dev0 and Dymola 2022x, per the Dymola "About Dymola" window, and found at least one unit test that failed the reference check that I didn't expect to (though insignificant to the human eye).  This makes me wonder if I'm running the tests with the right tool versions.  Is Dymola 2022x the same as ``docker pull "$DOCKER_USERNAME"/travis_ubuntu-1804_dymola:2022-x86_64_rev-1;``defined in the travis yml?  I also ran the tests in Ubuntu 20 instead of 18.  If not, I'll need to get the installation for that version of Dymola to run the tests and generate results for this PR.

2.  ``Buildings.Fluid.HeatExchangers.Validation.WetCoilCounterFlowLowWaterFlowRate`` is a test that is in the master and maint_9.0.x but isn't in maint_8.1.x.  The files I've pushed here add this test, but let me know if this shouldn't be added in the maintenance branch.  Then, per 1. above, we can generate the appropriate reference results.

### CODE REVIEW

**Comment by dhblum** [comment]
And depending on your answer to 2. above, I'll fix the failing test because WetCoilCounterFlowLowWaterFlowRate isn't in the package.order.

**Comment by mwetter** [comment]
@dhblum Dymola 2022x is different from `travis_ubuntu-1804_dymola:2022-x86_64_rev-1` (note that travis is 2022, not 2022x). The right version is
https://github.com/lbl-srg/modelica-buildings/blob/bbdf2c6b56e3ce584cdce138be644246cc651b2c/.travis.yml#L99

Adding a new test on the maintenance branch is fine.

**Comment by dhblum** [comment]
@mwetter I updated reference results for the Dymola version.  I also removed the test that was added in version 9 as it was throwing a division by zero error that might be fixed by something related to the update to version 9.  So then not sure if it belongs in a version 8 maintenance.  Although I didn't look into it any further.

**Review by mwetter — APPROVED** [review]

**Comment by dhblum** [comment]
@mwetter Turns out my unexplained simulation fails I mentioned to you in person were due to hard drive space issues on my end.  I've rerun unit tests, checked against previous commit https://github.com/lbl-srg/modelica-buildings/commit/dbad43cdeec9fe34d86e68beec7ba49b445878b6, and updated reference results.

**Comment by dhblum** [comment]
Jobs [.41](https://app.travis-ci.com/github/lbl-srg/modelica-buildings/jobs/588546192) and [.38](https://app.travis-ci.com/github/lbl-srg/modelica-buildings/jobs/588546189) were failing overnight due to stall, the only ones failing in the [Build](https://app.travis-ci.com/github/lbl-srg/modelica-buildings/builds/257818239).  I restarted them both and now they're both passing.

**Pull request merged**
