### PR TITLE
Issue1719 fix geometry params

### LINKED ISSUE #1719: Update geometry parameters
In `Examples.VAVReheat` fix an inconsistency in the geometry parameters.

### PR DESCRIPTION
**Pull request by milicag**
Closes #1719.

### CODE REVIEW

**Comment by mwetter** [comment]
@milicag Please also update `Buildings/package.mo` as this is where users most likely look for updates to the models.

**Comment by milicag** [comment]
@mwetter Should I add those notes to version 7_0_0?

**Comment by mwetter** [comment]
Yes, that should be for 7_0_0 as this will be the release that contains the changes.

**Comment by mwetter** [comment]
This is ready to merge when the tests pass.

**Pull request merged**
