### PR TITLE
Heating and cooling valve control signals

### PR DESCRIPTION
**Pull request by milicag**
This PR addresses #839. It adds a sequence that generates heating and cooling valve control signals based on  ASHRAE Guideline 36, Part 5.B.5, with applicable documentation, images and tests.

In addition, it assigns a default value to the time constant of the derivative block of the controller ```CDL.Continuous.LimPID``` [```Td = 0.1```]

### CODE REVIEW

**Comment by milicag** [comment]
Validation passing locally:
```
milica@ubuntu:~/repos/modelica-buildings/Buildings$ ../bin/runUnitTests.py -s Buildings.Controls.OBC.ASHRAE.G36.Atomic
Regression tests are only run for the following package:
  Buildings.Controls.OBC.ASHRAE.G36.Atomic
Using 4 of 4 processors to run unit tests.
Number of models   : 734
          blocks   : 257
          functions: 147
Generated 17 regression tests.

Script that runs unit tests had 0 warnings and 0 errors.

See 'simulator.log' for details.
Unit tests completed successfully.

Execution time = 99.478 s
```

**Comment by mwetter** [comment]
@milicag : 
The tests fail *after* the master is merged into your branch. The reason is
```
Check of Buildings.Controls.OBC.ASHRAE.G36.Atomic.Validation.HeatingAndCoolingCoilValves_LoopDisable:

Component type specifier CDL.Logical.GreaterEqualThreshold not found
```
as well as similar errors. This is because we moved these blocks to other packages. Can you please update this branch (`issue839_uhea_ucoo`) and then I can review tomorrow.

**Comment by milicag** [comment]
@mwetter Thanks, Michel, I added to our [PR checklist](https://docs.google.com/document/d/1Ic7McoO5UdUvfnfE5BVDWnWsDs4zA0lyQWSQ8C4zOSI/edit). I'll let you know when I push up the correction.

**Comment by mwetter** [comment]
- [ ] Refactor `Buildings.Controls.OBC.ASHRAE.G36.Atomic.HeatingAndCoolingCoilValves` as it has anti-windup, and because the inequality checks are not robust to numerical or sensor noise.

**Comment by milicag** [comment]
@mwetter I've introduced the changes we've discussed this morning, this is ready for review one tests pass.

**Comment by mwetter** [comment]
This is ready to merge when all tests pass.
I removed "control loop" from the documentation, as a loop is only formed once the controller and the plant is connected through a feedback loop.
I also moved the parameters to the first pane of the dialog, and corrected the documentation string.

This closes #839

**Pull request merged**
