### PR TITLE
Add optional switchover to PartialElectric for heat recovery chillers

### LINKED ISSUE #3211: Add optional switchover to PartialElectric for heat recovery chillers
Some heat recovery chillers have a built-in switchover option allowing for switching from cooling to heating mode, i.e., from tracking a chilled water supply temperature setpoint to tracking a hot water supply temperature setpoint.
This ticket is to implement this optional mode switching into `Buildings.Fluid.Chillers.BaseClasses.PartialElectric`.
The changes are ***backward compatible***.

### PR DESCRIPTION
**Pull request by AntoineGautier**
This closes #3211.
In addition, as part of this PR, some typos were corrected throughout the package `Fluid.Chillers`.
The changes introduced by this PR are ***backward compatible***.

### CODE REVIEW

**Comment by dhblum** [comment]
Thanks @AntoineGautier for this PR.  It's looking good to me.  I made one suggested edit to the TSet comment in https://github.com/lbl-srg/modelica-buildings/pull/3212/commits/ffa43f1d8ec849c1e444253d4417e89033465d0a.  I'm also thinking, does it make sense to calculate the COP of Heating by adding a variable ``COP_h`` if ``have_switchover`` is true and calculating using ``QCon_flow``?

**Comment by AntoineGautier** [comment]
Good idea! I added `COP_h` in [0bfc2da](https://github.com/lbl-srg/modelica-buildings/pull/3212/commits/0bfc2daaa80e86a11f4756d00da0b2fbc5508b61). Note that it needed to be added as a connector as conditional components can only be used in connections (per https://specification.modelica.org/maint/3.5/class-predefined-types-and-declarations.html#conditional-component-declaration). So I simply removed any graphical annotation so that from a user experience, it shows up as the same type of variable as `COP`.

**Comment by dhblum** [comment]
Sounds good on ``COP_h``, thanks Antoine for implementing that.  This PR is overall looking ready to me.

**Review by dhblum — APPROVED** [review]

**Review by mwetter — APPROVED** [review]

**Comment by mwetter** [comment]
@AntoineGautier : Thanks for correcting the typos. Can you please also patch the files in the IBPSA library, otherwise these changes will be overridden in the next merge of IBPSA.

**Comment by AntoineGautier** [comment]
@mwetter Of course (it slipped my mind). This is here https://github.com/ibpsa/modelica-ibpsa/pull/1688

**Pull request merged**
