### PR TITLE
Issue1413_isat

### PR DESCRIPTION
**Pull request by caryfaulkner**
Hi @JayHuLBL , @xuhan425 and I have finished addressing Dr. Wetter's comments. Please let me know of anything you need from us.

### CODE REVIEW

**Comment by JayHuLBL** [comment]
@caryfaulkner Would you please merge the changes in `lbl-srg:issue1413_isat` to your branch? `lbl-srg:issue1413_isat` has the latest master update. 

This will resolve the conflicts here.

**Comment by caryfaulkner** [comment]
> @caryfaulkner Would you please merge the changes in `lbl-srg:issue1413_isat` to your branch? `lbl-srg:issue1413_isat` has the latest master update.
> 
> This will resolve the conflicts here.

Sure, I have merged those changes @JayHuLBL. Let me know if you need anything else.

**Comment by JayHuLBL** [comment]
@caryfaulkner Thanks for the update. The conflicts are gone now. Would you please let me know what Dymola version are you running? Is it Dymola 2022, or Dymola 2022x? The isat models would fail the CI test as see here: https://app.travis-ci.com/github/lbl-srg/modelica-buildings/jobs/554984627. 
I cannot see the error in my local machine, as I am running Dymola 2022 on Ubuntu 18. The CI test is running Dymola 2022x and Ubuntu 20.04. See the [CI test settings](https://app.travis-ci.com/github/lbl-srg/modelica-buildings/builds/244574333/config). The model would fail to run with Dymola 2022x as:
```
sh -c "$DYMOLA/bin/dsbuild.sh -godess -x64 -I '/home/casper/gitRepo/modelica-buildings/Buildings/Resources/C-Sources' -I '/opt/dymola-2022x-x86_64/Modelica/Library/Modelica 4.0.0/Resources/C-Sources' -L '/home/casper/gitRepo/modelica-buildings/Buildings/Resources/Library/linux64' -L '/opt/dymola-2022x-x86_64/Modelica/Library/Modelica 4.0.0/Resources/Library/linux64'  -l ModelicaIO  -l ModelicaMatIO  -l ModelicaStandardTables  -l isat  -l zlib  dsmodel" failed.

Compilation of Buildings.ThermalZones.Detailed.Examples.ISAT.Tutorial.MixedConvection failed.

ERRORS have been issued.
```

**Comment by caryfaulkner** [comment]
> @caryfaulkner Thanks for the update. The conflicts are gone now. Would you please let me know what Dymola version are you running? Is it Dymola 2022, or Dymola 2022x? The isat models would fail the CI test as see here: https://app.travis-ci.com/github/lbl-srg/modelica-buildings/jobs/554984627. I cannot see the error in my local machine, as I am running Dymola 2022 on Ubuntu 18. The CI test is running Dymola 2022x and Ubuntu 20.04. See the [CI test settings](https://app.travis-ci.com/github/lbl-srg/modelica-buildings/builds/244574333/config). The model would fail to run with Dymola 2022x as:
> 
> ```
> sh -c "$DYMOLA/bin/dsbuild.sh -godess -x64 -I '/home/casper/gitRepo/modelica-buildings/Buildings/Resources/C-Sources' -I '/opt/dymola-2022x-x86_64/Modelica/Library/Modelica 4.0.0/Resources/C-Sources' -L '/home/casper/gitRepo/modelica-buildings/Buildings/Resources/Library/linux64' -L '/opt/dymola-2022x-x86_64/Modelica/Library/Modelica 4.0.0/Resources/Library/linux64'  -l ModelicaIO  -l ModelicaMatIO  -l ModelicaStandardTables  -l isat  -l zlib  dsmodel" failed.
> 
> Compilation of Buildings.ThermalZones.Detailed.Examples.ISAT.Tutorial.MixedConvection failed.
> 
> ERRORS have been issued.
> ```

@JayHuLBL I have not been using Dymola 2022x in Ubuntu 20.04 either. I am currently working on setting this up and testing the models in this environment. I will let you know of any updates I have.

**Comment by JayHuLBL** [comment]
@caryfaulkner Would you please let me know if you have any questions?

**Comment by caryfaulkner** [comment]
> @caryfaulkner Would you please let me know if you have any questions?

Hi @JayHuLBL , I have solved the issue with the models using Dymola 2022x in Ubuntu 20.04, but am having some issues with running unit tests for these models. I hope to address these this coming week and will let you know if I have any questions.

**Comment by caryfaulkner** [comment]
> @caryfaulkner Do you need help on addressing the issues?

Hi @JayHuLBL, thank you for reaching out. It appears there was another issue with the ISAT code that @xuhan425 and I have been working on addressing. We hope to solve this issue soon and get back to you.

**Comment by JayHuLBL** [comment]
@caryfaulkner @xuhan425 Thanks!

**Comment by JayHuLBL** [comment]
@caryfaulkner Hello Cary, did you have a chance to push your local files to your repo? I tried to run the models from the one in your local repo, but see some text like ([<<<<<<< HEAD](https://github.com/caryfaulkner/modelica-buildings/blob/661b756df88aac3dcdd7c5ff3f15f70e1a2fc1b5/Buildings/Resources/C-Sources/isatExchangeData.c#L99)). It seems that the one in your remote repo is not clean-up.

**Comment by caryfaulkner** [comment]
> @caryfaulkner Hello Cary, did you have a chance to push your local files to your repo? I tried to run the models from the one in your local repo, but see some text like ([<<<<<<< HEAD](https://github.com/caryfaulkner/modelica-buildings/blob/661b756df88aac3dcdd7c5ff3f15f70e1a2fc1b5/Buildings/Resources/C-Sources/isatExchangeData.c#L99)). It seems that the one in your remote repo is not clean-up.

@JayHuLBL Thanks for letting me know. I will fix that and get back to you soon.

**Comment by JayHuLBL** [comment]
@caryfaulkner Did you have a chance to clean up the code? Thanks!

**Comment by caryfaulkner** [comment]
> @caryfaulkner Did you have a chance to clean up the code? Thanks!

Hi @JayHuLBL, I just pushed the fix for this.

**Pull request merged**
