### PR TITLE
Issue2282 sample trigger and pulse: rename delay to shift

### LINKED ISSUE #2282: CDL: delay parameter in SampleTrigger and Pulse
Rename `delay` parameter in `Buildings.Controls.OBC.CDL.Logical.Sources.SampleTrigger`,  `Buildings.Controls.OBC.CDL.Logical.Sources.Pulse`, `Buildings.Controls.OBC.CDL.Continuous.Sources.Pulse`, and `Buildings.Controls.OBC.CDL.Integers.Sources.Pulse` to `shift`.

### PR DESCRIPTION
**Pull request by milicag**
Closes #2282.

### CODE REVIEW

**Review by mwetter — CHANGES_REQUESTED** [review]
@milicag : This is not the right fix. It essentially reverses the change done through https://github.com/lbl-srg/modelica-buildings/issues/2170

The problem in this new implementation is just with the mod( , ) function if arguments are equal but non-zero. Please correct this in a robust way.

**Comment by milicag** [comment]
@mwetter Just to make sure I understand the control intent of the blosk, you would like the sampler to always sample at times where values mod(time, period) = 0, but not until the delay time has elapsed?

**Comment by mwetter** [comment]
The delay is not a time that need to elapse, but rather a shift in time,
see figure in Buildings.Controls.OBC.CDL.Logical.Sources.SampleTrigger

**Comment by milicag** [comment]
So why don't we call it `shift` parameter?

**Comment by mwetter** [comment]
That may be more suitable. Can you please make the change (and update conversion scripts if we used this before) and also update the figures. The same applies to similar blocks, such as `Pulse`.

**Comment by milicag** [comment]
@mwetter Should I remove release notes that are deprecated through revisions within the same release cycle?

**Comment by mwetter** [comment]
@milicag : Release notes should only show what changed relative to previous releases, so if there are notes that we reverted, they should be removed. The same applies to the conversion script. Both are meant for official releases only.

**Comment by milicag** [comment]
@mwetter As I assumed. I will go through both conversion script and release notes and remove redundancies. There was, for example, a version that specifies a number of periods for the pulse that is now removed.

**Review by mwetter — APPROVED** [review]

**Comment by mwetter** [comment]
@milicag : What's the purpose of https://github.com/lbl-srg/modelica-buildings/pull/2283/commits/8bc9b022ddbb5fc09afaf0e9c0b9b198c56031ba?

**Comment by milicag** [comment]
@mwetter I just merge the master in. It looks like git allowed me to push an empty commit. I thought there were a few changes to the master, as I had them locally. If the remote was identical I expected git to be clever about it. Sorry for delaying the test. I merged this already into the chiller plants branch.

**Pull request merged**
