### PR TITLE
Issue1421 python

### LINKED ISSUE #1421: setting the PYTHONPATH variable fails on some Linux installations
For `Utilities.IO.Python27`, setting the `PYTHONPATH` fails in some linux installations.

### PR DESCRIPTION
**Pull request by mwetter**
This closes #1421

Todo
- [x] Produce binary for Linux 32 bit
- [x] Produce binary for Windows 32 bit
- [x] Produce binary for Windows 64 bit

### CODE REVIEW

**Comment by AntoineGautier** [comment]
@mwetter 
Travis check succeeds with the development branch of `buildingspy` `issue245_funnelIntegration` after correcting the conditional statement used to launch simulations with JModelica:
`self._data[i]["mustExportFMU"] or self._data[i]["mustSimulate"])` replaced by `self._data[i]['jmodelica']['simulate']`.
I am about to make a PR in `buildingspy`. Once it is done I will generate the missing binaries and push them here.

**Comment by AntoineGautier** [comment]
@mwetter I get the following error log when compiling on Win64 (sorry it's in French...). 
Should I go into debugging or you have a quick look first?
```
Windows 64 bit compilation activated.
Compilateur d'optimisation Microsoft (R) C/C++ version 19.16.27025.1 pour x64
Copyright (C) Microsoft Corporation. Tous droits réservés.

dummy.c
Microsoft (R) Incremental Linker Version 14.16.27025.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:dummy.dll
/dll
/implib:dummy.lib
/out:python2.7.dll
dummy.obj
Compilateur d'optimisation Microsoft (R) C/C++ version 19.16.27025.1 pour x64
Copyright (C) Microsoft Corporation. Tous droits réservés.

pythonInterpreter.c
c:\users\agautier\modelica-buildings\buildings\resources\src\python\pythonObjectStructure.h(24): error C2059: erreur de syntaxe : 'chaîne'
c:\users\agautier\modelica-buildings\buildings\resources\src\python\pythonObjectStructure.h(25): error C2059: erreur de syntaxe : '}'
pythonInterpreter.c(12): warning C4273: 'initPythonMemory' : liaison DLL incohérente
c:\users\agautier\modelica-buildings\buildings\resources\src\python\pythonInterpreter.h(90): note: voir la définition précédente de 'initPythonMemory'
pythonInterpreter.c(13): error C2065: 'pythonPtr' : identificateur non déclaré
pythonInterpreter.c(13): error C2065: 'ptr' : identificateur non déclaré
pythonInterpreter.c(13): warning C4047: '=' : les niveaux d'indirection de 'int' et de 'void *' sont différents
pythonInterpreter.c(13): error C2106: '=' : l'opérande gauche doit être une l-value
pythonInterpreter.c(15): error C2065: 'ptr' : identificateur non déclaré
pythonInterpreter.c(15): error C2223: la partie gauche de '->ptr' doit pointer vers struct/union
pythonInterpreter.c(16): error C2065: 'ptr' : identificateur non déclaré
pythonInterpreter.c(16): error C2223: la partie gauche de '->isInitialized' doit pointer vers struct/union
pythonInterpreter.c(17): error C2065: 'ptr' : identificateur non déclaré
pythonInterpreter.c(17): error C2223: la partie gauche de '->pModule' doit pointer vers struct/union
pythonInterpreter.c(18): error C2065: 'ptr' : identificateur non déclaré
pythonInterpreter.c(18): error C2223: la partie gauche de '->pFunc' doit pointer vers struct/union
pythonInterpreter.c(19): error C2065: 'ptr' : identificateur non déclaré
pythonInterpreter.c(19): error C2059: erreur de syntaxe : 'chaîne'
pythonInterpreter.c(20): warning C4312: 'cast de type' : la conversion de 'int' en 'void *' d'une taille supérieure
pythonInterpreter.c(26): error C2146: erreur de syntaxe : absence de ')' avant l'identificateur 'nDblWri'
pythonInterpreter.c(26): error C2081: 'size_t' : nom non conforme dans la liste de paramètres formels
pythonInterpreter.c(26): error C2061: erreur de syntaxe : identificateur 'nDblWri'
pythonInterpreter.c(26): error C2059: erreur de syntaxe : ';'
pythonInterpreter.c(26): error C2059: erreur de syntaxe : ','
pythonInterpreter.c(435): warning C4273: 'freePythonMemory' : liaison DLL incohérente
c:\users\agautier\modelica-buildings\buildings\resources\src\python\pythonInterpreter.h(92): note: voir la définition précédente de 'freePythonMemory'
pythonInterpreter.c(437): error C2059: erreur de syntaxe : ')'
pythonInterpreter.c(438): error C2059: erreur de syntaxe : 'chaîne'
pythonInterpreter.c(439): warning C4022: 'free' : incompatibilité de pointeur pour le paramètre réel 1
Compilateur d'optimisation Microsoft (R) C/C++ version 19.16.27025.1 pour x64
Copyright (C) Microsoft Corporation. Tous droits réservés.
```

**Comment by mwetter** [comment]
It looks like it already fails when parsing `pythonObjectStructure.h`, but not much changed for this file:
```bash
$ git log ./Buildings/Resources/src/python/pythonObjectStructure.h
commit 4fa890c4bade9b5ef29c752ac65892e83ae32d95
Author: Michael Wetter <mwetter@lbl.gov>
Date:   Wed Apr 24 16:07:03 2019 -0700

    Refactored python API

commit aa5b566e481749e75655fe72a31fbaff04b0ed30
Author: Michael Wetter <mwetter@lbl.gov>
Date:   Thu Feb 1 09:19:52 2018 -0800

    Refactored implementation to make SimpleRoom about 20% faster [ci skip]
$ git diff aa5b566e481749e75655fe72a31fbaff04b0ed30 ./Buildings/Resources/src/python/pythonObjectStructure.h
diff --git a/Buildings/Resources/src/python/pythonObjectStructure.h b/Buildings/Resources/src/python/pythonObjectStructure.h
index 0a701f4ab..4e5d00188 100644
--- a/Buildings/Resources/src/python/pythonObjectStructure.h
+++ b/Buildings/Resources/src/python/pythonObjectStructure.h
@@ -21,6 +21,7 @@ typedef struct pythonPtr
   int isInitialized;
   PyObject* pModule;
   PyObject* pFunc;
+  char* PYTHONPATH;
 } pythonPtr;
 
 #endif
```
Can you please see what causes this failure on Windows.

**Comment by AntoineGautier** [comment]
The preprocessor uses the following definition from `C:\Python27\include\pyconfig.h`:
```
#ifndef PYTHONPATH
#	define PYTHONPATH ".\\DLLs;.\\lib;.\\lib\\plat-win;.\\lib\\lib-tk"
#endif
```
Which includes a string literal in the `struct` declaration (not allowed).
By changing the name of the `stuct` member to `pythonPath` the error is fixed. 
In `testProgram.c` the call to `pythonExchangeValuesNoModelica` is then done using `pypath` from `char *pypath = getenv("PYTHONPATH")`.
Does this make sense to you? (I will upload the code that compiles).

Furthermore I add to include [this fix](https://stackoverflow.com/a/46480387) for `asprintf` function which is not available in Windows C library.

**Comment by AntoineGautier** [comment]
@mwetter I updated the batch file for compiling on Windows. Note that the test needed `PYTHONHOME` to be defined on Windows (or `Py_Initialize()` failed).
Tests are run successfully on Linux 64 & 32 and Windows 64 & 32.

**Comment by mwetter** [comment]
@AntoineGautier 
This pull request can be closed as it is replaced by https://github.com/lbl-srg/modelica-buildings/pull/1433
It must not be merged to the master because https://github.com/lbl-srg/modelica-buildings/pull/1422/commits/1ef4779af74ef29b829ea73f55d01b157d16d6bf mistakenly merged the Spawn development branch which is not ready to be merged to the master.
Please go ahead and close this branch without merging it.

**Comment by mwetter** [comment]
I close this as it is replaced by https://github.com/lbl-srg/modelica-buildings/pull/1433

**Pull request closed without merging**
