### PR TITLE
install scipy, numpy and matplotlib via pip

### PR DESCRIPTION
**Pull request by thorade**
install scipy, numpy and matplotlib v
instead of using system_site_packages
https://docs.travis-ci.com/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs

### CODE REVIEW

**Comment by thorade** [comment]
https://travis-ci.org/lbl-srg/modelica-buildings/pull_requests
Docker login failed.

**Comment by mwetter** [comment]
Merged to thorade-travis_pip_apt for testing

**Comment by thorade** [comment]
Once this is merged, one could try whether using the pip cache brings any speedup:
https://docs.travis-ci.com/user/caching/#pip-cache

**Comment by thorade** [comment]
BTW: Travis says "2 checks passed" and there are indeed two builds in the build history with different times.

**Pull request merged**
