### PR TITLE
Enabled JModelica tests for all Python examples

### LINKED ISSUE #1578: Enable Python examples for JModelica CI testing
This issue is to enable the CI testing for
`Buildings.Utilities.IO.Python27.Examples.KalmanFilter` and
`Buildings.Utilities.IO.Python27.Functions.Examples.Exchange`
for JModelica.

### PR DESCRIPTION
**Pull request by mwetter**
This closes #1578

### CODE REVIEW

**Comment by mwetter** [comment]
The following command works:
```
export PYTHONPATH=$PYTHONPATH:`pwd`/Buildings/Resources/Python-Sources
jm_ipython.sh jmodelica.py Buildings.Utilities.IO.Python27.Examples.SimpleRoom
```

**Comment by mwetter** [comment]
There is some non-repeatable behavior, see `KeyError: 0`:
```bash
$ ../bin/runUnitTests.py --batch --single-package "Buildings.Utilities.IO.Python27.Examples" -n 2 --tool jmodelica --skip-verification
Regression tests are only run for the following package:
  Buildings.Utilities.IO.Python27.Examples
Time series of simulation results will not be verified.
Using 2 of 48 processors to run unit tests for jmodelica.
Number of models   : 1030
          blocks   : 332
          functions: 200
Generated 2 regression tests.

Script that runs unit tests had 0 warnings and 0 errors.

See 'simulator-jmodelica.log' for details.
Unit tests completed successfully.

Did not delete temporary directory /tmp/tmp-Buildings-0-NtiKSc
Did not delete temporary directory /tmp/tmp-Buildings-1-mgBaEQ
Execution time = 7.890 s
$ ../bin/runUnitTests.py --batch --single-package "Buildings.Utilities.IO.Python27.Examples" -n 2 --tool jmodelica --skip-verification
Regression tests are only run for the following package:
  Buildings.Utilities.IO.Python27.Examples
Time series of simulation results will not be verified.
Using 2 of 48 processors to run unit tests for jmodelica.
Number of models   : 1030
          blocks   : 332
          functions: 200
Generated 2 regression tests.

*** Error: Simulation of Buildings.Utilities.IO.Python27.Examples.KalmanFilter failed with KeyError: 0.

Number of models that translated but failed simulation       : 1
Script that runs unit tests had 0 warnings and 1 errors.

See 'simulator-jmodelica.log' for details.
Did not delete temporary directory /tmp/tmp-Buildings-0-Saz06X
Did not delete temporary directory /tmp/tmp-Buildings-1-t4SC1L
Execution time = 7.271 s
```
and
```
$ cat /tmp/tmp-Buildings-1-t4SC1L/Buildings_Utilities_IO_Python27_Examples_KalmanFilter_run.json 
{
    "model": "Buildings.Utilities.IO.Python27.Examples.KalmanFilter", 
    "translation": {
        "fmu_name": "/mnt/shared/tmp-Buildings-1-t4SC1L/./Buildings_Utilities_IO_Python27_Examples_KalmanFilter.fmu", 
        "cpu_time": 2.2758688926696777, 
        "success": true, 
        "stdout": [
            "Compliance warning at line 31, column 19, in file '/mnt/tmp/tmp-Buildings-1-t4SC1L/Buildings/Utilities/IO/Python27/Examples/KalmanFilter.mo':", 
            "  The terminal() function-like operator is not supported, and is currently evaluated to false", 
            "sources/Buildings_Utilities_IO_Python27_Examples_KalmanFilter_funcs.c: In function 'func_Modelica_Utilities_Strings_substring_def5':", 
            "sources/Buildings_Utilities_IO_Python27_Examples_KalmanFilter_funcs.c:173:14: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]", 
            "     result_v = ModelicaStrings_substring(string_v, tmp_1, tmp_2);", 
            "              ^", 
            "sources/Buildings_Utilities_IO_Python27_Examples_KalmanFilter_funcs.c: In function 'func_Modelica_Utilities_System_getEnvironmentVariable_def9':", 
            "sources/Buildings_Utilities_IO_Python27_Examples_KalmanFilter_funcs.c:261:44: warning: passing argument 3 of 'ModelicaInternal_getenv' from incompatible pointer type [-Wincompatible-pointer-types]", 
            "     ModelicaInternal_getenv(name_v, tmp_1, &content_v, &tmp_2);", 
            "                                            ^", 
            "sources/Buildings_Utilities_IO_Python27_Examples_KalmanFilter_funcs.c:257:17: note: expected 'const char **' but argument is of type 'char **'", 
            "     extern void ModelicaInternal_getenv(const char*, int, const char**, int*);", 
            "                 ^~~~~~~~~~~~~~~~~~~~~~~", 
            "sources/Buildings_Utilities_IO_Python27_Examples_KalmanFilter_funcs.c: In function 'func_Buildings_Utilities_IO_Python27_Functions_BaseClasses_exchange_def10':", 
            "sources/Buildings_Utilities_IO_Python27_Examples_KalmanFilter_funcs.c:305:152: warning: passing argument 12 of 'pythonExchangeValues' from incompatible pointer type [-Wincompatible-pointer-types]", 
            "     pythonExchangeValues(moduleName_v, functionName_v, pythonPath_v, dblWri_a->var, tmp_1, dblRea_a->var, tmp_2, tmp_3->var, tmp_4, tmp_5->var, tmp_6, strWri_a->var, tmp_7, pytObj_v, tmp_8);", 
            "                                                                                                                                                        ^~~~~~~~", 
            "In file included from sources/Buildings_Utilities_IO_Python27_Examples_KalmanFilter_funcs.c:2:0:", 
            "/mnt/tmp/tmp-Buildings-1-t4SC1L/Buildings/Resources/C-Sources/python27Wrapper.c:23:6: note: expected 'const char **' but argument is of type 'char **'", 
            " void pythonExchangeValues(const char * moduleName,", 
            "      ^~~~~~~~~~~~~~~~~~~~", 
            "/usr/local/JModelica/bin/../lib/RuntimeLibrary/libModelicaExternalC.a(ModelicaInternal.c.o): In function `ModelicaInternal_temporaryFileName':", 
            "/usr/local/src/JModelica/ThirdParty/MSL/Modelica/Resources/C-Sources/ModelicaInternal.c:657: warning: the use of `tmpnam' is dangerous, better use `mkstemp'", 
            "", 
            ""
        ]
    }, 
    "simulation": {
        "exception": "KeyError: 0", 
        "traceback": "Traceback (most recent call last):\n  File \"Buildings_Utilities_IO_Python27_Examples_KalmanFilter.py\", line 221, in run\n    ret_dic = process_with_timeout(target=_simulate, timeout=time_out)\n  File \"Buildings_Utilities_IO_Python27_Examples_KalmanFilter.py\", line 106, in process_with_timeout\n    ret = copy.copy(return_dict[0])\n  File \"<string>\", line 2, in __getitem__\n  File \"/usr/lib/python2.7/multiprocessing/managers.py\", line 774, in _callmethod\n    raise convert_to_error(kind, result)\nKeyError: 0\n", 
        "success": false
    }
}

```

**Comment by AntoineGautier** [comment]
It seems like `_simulate` in `development/jmodelica_run.template` terminates without returning (I guess a segmentation fault in `mod.simulate` could be a reason). So `return_dict` is not populated which leads to the misleading `KeyError` exception when trying to access `return_dict[0]` in `process_with_timeout`. One quick way around would be to guard against a `KeyError` in that function but that will not solve the original issue.

**Comment by mwetter** [comment]
This is being addressed through https://github.com/lbl-srg/modelica-buildings/issues/1587

**Comment by mwetter** [comment]
Closed because of https://github.com/lbl-srg/modelica-buildings/pull/1759

**Pull request closed without merging**
