### PR TITLE
Issue1502 replaceable thermal zone oa

### PR DESCRIPTION
**Pull request by AntoineGautier**
This PR addresses

1. the issues related to the minimum outdoor air flow rate as reported in #2019 (significant impact expected on simulation),
2. the incorrect connection of set-point and measurement signals for `yOATFre` in `Buildings.Examples.VAVReheat.Controls.Economizer` as reported in #1995 (no impact on simulation).

The impact on annual energy use is being assessed. It will be documented in this PR before merging.

@JayHuLBL Could you please review the first point? And also verify the issue of the default value for `yMin` as described in #2019. I did not modify the models yet because there might be a reason I do not know for the current default.

@kuzha Could you please review the second point?

### CODE REVIEW

**Comment by AntoineGautier** [comment]
The new settings for the gain and integral time in G36 AHU controller lead to non convergence issues such as

```
ERROR: Failed to solve nonlinear system using Newton solver.
  Time: 5463672.030250992
  Tag: simulation.nonlinear[5]

  For debugging help refer to the first error message of this type.

  Jacobian inverse norm estimate: 1.64691e+06
  Condition number estimate: 346875
  1-norm of the residual = 0.420988

  Last value of the solution:
    amb.ports[2].m_flow = 0.0950916
    dpRetDuc.port_a.m_flow = -0.0989388
    amb.ports[1].m_flow = -3.94233E-07
```

**Comment by JayHuLBL** [comment]
@AntoineGautier I noticed that you changed the value of zone minimum airflow setpoint, like `conVAVCor.VDisSetMin_flow`, from its default value of `0.15*V_flow_nominal` to the value for ventilation purpose, `(ratOAFlo_P * ratP_A + ratOAFlo_A) * AFloCor / effZ`. Note that the minimum airflow setpoint `VDisSetMin_flow` should be a value provided by the system designer as specified in section 3.1.2.2 of the Guideline 36 official release. Not sure if this change will affect the final results much.

See below my suggestions responding #2019:
1. In block `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.Economizers.Controller`, 
   - the input `uTSup` is output from `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.SetPoints.SupplySignals` which generates the supply temperature loop signal, with heating `[-1, 0]` and cooling `[0, 1]`. The `uTSup` was then used in block `mod` for modulating return and outdoor air damper position.
   - Also note that in both `mod` and `damLim`, there are parameter `uRetDamMin`. But they are different -- one is based on the control of the outdoor airflow rate and the other one is based on the supply temperature control loop signal `uTSup`.
2. In block `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.Controller`,
   - `yMinDamLim=0` and `yMaxDamLim=1` are not used. I believe it intents to be used by `eco.damLim` for the constant `yMin` and `yMax` (since the `yMinDamLim` and `yMaxDamLim` are in tab `economizer` and group `Damper limit`). These two constants `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.Economizers.Subsequences.Limits` originally might be `parameter` but at some point were changed to `constant`.

Suggest to do following:
1. Delete `yMinDamLim=0` and `yMaxDamLim=1` in block `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.Controller`. 
2. In `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.Economizers.Subsequences.Limits`:
    - change the values of constant `yMin` and `yMax`  to be `0` and `1` and remove their annotation for `group` and `tab`.
    - keep the default value of parameter `uRetDamMin` to be 0.5.
3. In `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.Economizers.Controller`,
    - create a new parameter like below and assign it to `damLim.uRetDamLim`
    ```
        parameter Real uRetDamMinLim(
            final min=0,
            final max=1,
            final unit="1") = 0.5
            "Minimum control signal for the return air damper position limit, for specifying limits of the return and outdoor air damper position"
        annotation (Dialog(tab="Commissioning", group="Controller"));
    ```
4. The parameter `uRetDamMinLim` can then be propagated to the controller `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.Controller` and put it the in the tab `Economizer` and group `Damper limits`.
5. The block `Buildings.Controls.OBC.ASHRAE.G36_PR1.TerminalUnits.Reheat.SetPoints.ActiveAirFlow` is to calculate the min/max occupied flow rate, not the outdoor airflow rate. There is no requirement to consider the distribution effectiveness when specifying the min/max flow rate. In addition, the implementation is based on the Guideline36_PR1 section 5.E.3-5, which corresponded to section 5.6.4-5 of the G36 official release.
6. `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.SetPoints.OutdoorAirFlow.Zone` and `Buildings.Controls.OBC.ASHRAE.G36_PR1.TerminalUnits.Controller` assumes if there is occupancy sensor, it will not just show whether or not the zone is occupied, but also could count how many people in the zone. It would be too advanced now. We could keep it for now as the case study assumes that there is no occupancy sensor so this input will not show anyway. We can refactor it in the process of upgrading to G36 official release version.

**Comment by AntoineGautier** [comment]
@JayHuLBL 

About the zone minimum airflow setpoint: my mistake. I forgot to increase the zone minimum outdoor air flow rate as specified in ASHRAE 62.1-2019 §6.2.4.3.2. _"Zone Minimum Primary Airflow. For each zone, the minimum primary air- flow (Vpz-min) shall be determined in accordance with Equation 6-9. Vpz-min = Voz × 1.5"_. I suggest to adopt this default for Guideline 36. This leads to a percentage between 11% and 19% of the zone maximum primary air flow rate. This also satisfies the requirement from G36 §3.1.2.2 "select Vmin to prevent creating critical zones" as all zones then have the same Zpz value.

About your suggestions

1. Delete `yMinDamLim=0` and `yMaxDamLim=1` in block `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.Controller`.

Agreed and implemented.

2. In `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.Economizers.Subsequences.Limits`:
    - change the values of constant `yMin` and `yMax`  to be `0` and `1` and remove their annotation for `group` and `tab`.
    - keep the default value of parameter `uRetDamMin` to be 0.5.

Agreed and implemented.

3. In `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.Economizers.Controller`,
    - create a new parameter like below and assign it to `damLim.uRetDamLim`
    ```
        parameter Real uRetDamMinLim(
            final min=0,
            final max=1,
            final unit="1") = 0.5
            "Minimum control signal for the return air damper position limit, for specifying limits of the return and outdoor air damper position"
        annotation (Dialog(tab="Commissioning", group="Controller"));
    ```

Agreed and implemented.
I further suggest a different wording and to split the group "Controller" into "Minimum outdoor air control" and "Supply air temperature control", see my commit.

4. The parameter `uRetDamMinLim` can then be propagated to the controller `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.Controller` and put it the in the tab `Economizer` and group `Damper limits`.

I wonder if it is worth exposing this parameter though. From G36 Figure 5.16.6.3 I do not see any specification that this value should be adjustable.

5. The block `Buildings.Controls.OBC.ASHRAE.G36_PR1.TerminalUnits.Reheat.SetPoints.ActiveAirFlow` is to calculate the min/max occupied flow rate, not the outdoor airflow rate. There is no requirement to consider the distribution effectiveness when specifying the min/max flow rate. In addition, the implementation is based on the Guideline36_PR1 section 5.E.3-5, which corresponded to section 5.6.4-5 of the G36 official release.

I agree, sorry for the confusion.

6. `Buildings.Controls.OBC.ASHRAE.G36_PR1.AHUs.MultiZone.VAV.SetPoints.OutdoorAirFlow.Zone` and `Buildings.Controls.OBC.ASHRAE.G36_PR1.TerminalUnits.Controller` assumes if there is occupancy sensor, it will not just show whether or not the zone is occupied, but also could count how many people in the zone. It would be too advanced now. We could keep it for now as the case study assumes that there is no occupancy sensor so this input will not show anyway. We can refactor it in the process of upgrading to G36 official release version.

I cannot see any kind of occupancy sensor returning the number of people in the zone. Also consider G36 §4.2 VAV Terminal Unit with Reheat, where the optional occupancy sensor is listed as DI (not AI). We should open a specific issue I believe, although I agree that this is not a priority.

**Comment by AntoineGautier** [comment]
With the updates from this PR the annual energy use is now
```
.. table:: Heating, cooling, fan and total site HVAC energy, and savings of guideline 36 case versus base case.

   ===================================== ===================================== ====================================== ====================================== =====
   :math:`E_{h} \quad [kWh/(m^2\,a)]`    :math:`E_{c} \quad [kWh/(m^2\,a)]`    :math:`E_{f} \quad [kWh/(m^2\,a)]`     :math:`E_{tot} \quad [kWh/(m^2\,a)]`     [%]
   ===================================== ===================================== ====================================== ====================================== =====
                                   9.577                                 15.46                                  2.093                                  27.13   
                                   7.565                                  10.8                                  1.154                                  19.52  28.0 
   ===================================== ===================================== ====================================== ====================================== =====
```

**Comment by AntoineGautier** [comment]
TODO

- [ ] Add revision notes.

**Comment by AntoineGautier** [comment]
This is closed as it will be addressed through `issue2019_VAV_MinOA` to be merged into the master first.

**Pull request closed without merging**
