### PR TITLE
Issue1463 chiller absorption indirect

### LINKED ISSUE #1463: add absorption chiller
This issue is to add a model similar to the EnergyPlus model `Chiller:Absorption:Indirect`, including examples and validation against the EnergyPlus model.
The development branch is `issue1463_ChillerAbsorptionIndirect`.

### PR DESCRIPTION
**Pull request by mwetter**
This closes #1463

### CODE REVIEW

**Comment by mwetter** [comment]
To do before merging:
- [ ] For EnergyPlus verification, upload idf file and script that produces data tables in .mos format.
- [ ] For EnergyPlus verification, use data reader from file, configured to be using piece-wise constant values.

**Comment by Helarga** [comment]
> To do before merging:
> 
> * [ *]  For EnergyPlus verification, upload idf file and script that produces data tables in .mos format.
> * [* ]  For EnergyPlus verification, use data reader from file, configured to be using piece-wise constant values.

Fatto!

**Comment by mwetter** [comment]
@Helarga : Can you please address the items below and make a new pull request against this branch

- [ ] Updated idf file `IndirectAbsorptionChiller.idf` to EnergyPlus 9.2
- [ ] Run it with `cd Resources/Data/Fluid/Chillers/IndirectAbsorptionChiller && ./run_IndirectAbsorptionChiller.sh`
- [ ] In `modelica.csv` remove time series that are not needed by Modelica. It currently has 70 columns.
- [ ] In `csv_to_mos_IndirectAbsorptionChiller.py`, print data with a statement like `"{time:6d} {TOut:0.2f} {TCor:0.3f} {TSou:0.3f} {TEas:0.3f} {TNor:0.3f} {TWes:0.3f} {TAtt:0.3f}".format(**data)` (to reduce the number of digits and thereby also the file size). See for example https://github.com/lbl-srg/modelica-buildings/blob/issue1581_spawn_output_variables/Buildings/Resources/Data/Experimental/EnergyPlus/Validation/csv_to_mos_RefBldgSmallOfficeNew2004_Chicago.py#L7
- [ ]  In `csv_to_mos_IndirectAbsorptionChiller.py`, print first data row twice (because EnergyPlus uses as the first output the values at t=1min) and reduce the output to hours 6 to 9 as not much happens outside these hours. Now the file is 1.9M large. Then, the validation can be updated to only simulate this time period.

**Comment by Helarga** [comment]
> @Helarga : Can you please address the items below and make a new pull request against this branch
> 
> [ * ]  Updated idf file `IndirectAbsorptionChiller.idf` to EnergyPlus 9.2
> [*]  Run it with `cd Resources/Data/Fluid/Chillers/IndirectAbsorptionChiller && ./run_IndirectAbsorptionChiller.sh`
> * [ *]  In `modelica.csv` remove time series that are not needed by Modelica. It currently has 70 columns.
> * [ *]  In `csv_to_mos_IndirectAbsorptionChiller.py`, print data with a statement like `"{time:6d} {TOut:0.2f} {TCor:0.3f} {TSou:0.3f} {TEas:0.3f} {TNor:0.3f} {TWes:0.3f} {TAtt:0.3f}".format(**data)` (to reduce the number of digits and thereby also the file size). See for example https://github.com/lbl-srg/modelica-buildings/blob/issue1581_spawn_output_variables/Buildings/Resources/Data/Experimental/EnergyPlus/Validation/csv_to_mos_RefBldgSmallOfficeNew2004_Chicago.py#L7
> * [* ]   In `csv_to_mos_IndirectAbsorptionChiller.py`, print first data row twice (because EnergyPlus uses as the first output the values at t=1min) and reduce the output to hours 6 to 9 as not much happens outside these hours. Now the file is 1.9M large. Then, the validation can be updated to only simulate this time period.

**Comment by mwetter** [comment]
This is ready to merge when all tests pass.

**Pull request merged**
