### PR TITLE
Issue2725 boiler heat correction

### LINKED ISSUE #2725: Correct boiler heat flow with loss to the ambient
First discussed in comments in #2695.
In `Buildings.Fluid.Boilers`, the thermal conduction between the boiler and the ambient is considered (via `UAOve`), but this is factored into the calculation of the heat from the fuel to the working fluid `QWat_flow`.
This part of the calculation is also explained in the documentation.

### PR DESCRIPTION
**Pull request by hcasperfu**
This closes #2725.

### CODE REVIEW

**Comment by hcasperfu** [comment]
In `Buildings.Fluid.Boilers.BaseClasses.PartialBoiler`, the equation `QWat_flow = eta * QFue_flow` is changed to `QWat_flow = eta * QFue_flow + UAOve.Q_flow` to account for the boiler's heat loss to the ambient. In the new equation, the heat loss is "added" instead of "subtracted" because the direction of `UAOve.Q_flow` is from the ambient to the boiler. 
Outside of the `Boilers` package, two models which directly or indirectly use the revised model had changed results when run through unit tests locally on my side. However, because I use Ubuntu 20 instead of Ubuntu 18 which causes some minor computation differences, I would need help from someone else to verify the results. 

- `Buildings.Examples.HydronicHeating.TwoRoomsWithStorage`'s results have been updated in 5a41d37.
- `Buildings.Examples.Tutorial.CDL.System5`'s results are updated in 9464ee0. The changes are very small and I suspect that they are caused by the Ubuntu version difference rather than the modified model. 

I have also improved the documentation of the `Boilers` package so that the equations in `package.mo` correspond to those in the code of `.BaseClasses.PartialBoiler` in the exactly same order. Explanatory texts have been rearranged to improve clarity. Some duplicate or redundant texts left behind from #2695 have been cleaned out.

**Comment by hcasperfu** [comment]
@mwetter: Please advise how I should update the release notes for this PR. `Buildings.Fluid.Boilers.BaseClasses.PartialBoiler` was created in #2695 and now changed again.

**Comment by mwetter** [comment]
> @mwetter: Please advise how I should update the release notes for this PR. `Buildings.Fluid.Boilers.BaseClasses.PartialBoiler` was created in #2695 and now changed again.

@hcasperfu : Please merge the latest master to this branch, and then edit the release notes as if both pull requests were one change. At the end, the release notes should show what is different between release 8.0.0 and the next release (9.0.0)

**Review by mwetter — APPROVED** [review]

**Comment by JayHuLBL** [comment]
@hcasperfu @mwetter The UTF-8 BOM was introduced in the model `Buildings.Fluid.Boilers.Data.Lochinvar.package.mo`. Because of this, **ANTLR** (so that **modelica-json**) cannot parse the model, it gives following error:
```
error:   *** Error when parsing /home/jianjun/GitFolder/modelica-buildings/Buildings//Fluid/Boilers/Data/Lochinvar/FTXL/package.mo: "line 1:0 token recognition error at: '﻿'
".
/home/jianjun/GitFolder/modelica-json/lib/modelicaToJSON.js:36
    throw new Error(msg)
    ^
```

I then removed the BOM through commit 95ce003, see the difference showing in my local machine:

```
jianjun@jianjun-virtual-machine:~/GitFolder/modelica-buildings/Buildings$ git diff Fluid/Boilers/Data/Lochinvar/FTXL/package.mo
diff --git a/Buildings/Fluid/Boilers/Data/Lochinvar/FTXL/package.mo b/Buildings/Fluid/Boilers/Data/Lochinvar/FTXL/package.mo
index 8b29ef1426..e6c48a0d49 100644
--- a/Buildings/Fluid/Boilers/Data/Lochinvar/FTXL/package.mo
+++ b/Buildings/Fluid/Boilers/Data/Lochinvar/FTXL/package.mo
@@ -1,4 +1,4 @@
-<U+FEFF>within Buildings.Fluid.Boilers.Data.Lochinvar;
+within Buildings.Fluid.Boilers.Data.Lochinvar;
 package FTXL "Package with performance data for Lochinvar FTXL™ Fire Tube boilers"
   extends Modelica.Icons.Package;
```

**Comment by hcasperfu** [comment]
In 4952a77, I reverted the updated results for `Buildings.Examples.Tutorial.CDL.System5` since Travis threw a warning. Travis disagreed with the new results that I suspected were changed due to OS difference rather than model update.

**Pull request merged**
