### PR TITLE
Replace cooling coil model

### LINKED ISSUE #2549: Replace cooling coil model
This issue is to replace the instances of `Buildings.Fluid.HeatExchangers.WetCoilCounterFlow` in the library and rather use `Buildings.Fluid.HeatExchangers.WetCoilEffectivenessNTU`.

### PR DESCRIPTION
**Pull request by AntoineGautier**
This closes #2549.

### CODE REVIEW

**Comment by AntoineGautier** [comment]
Note that with the new cooling coil model, the models in `Buildings/Examples/VAVReheat` fail to simulate with JModelica. They have been excluded from the CI tests.

**Comment by JayHuLBL** [comment]
@AntoineGautier The changes are good to me, just need change back the `.travis.yml`.

**Review by JayHuLBL — APPROVED** [review]

**Comment by AntoineGautier** [comment]
TODO before merging:

- [ ] Update cooling FCU models in `Buildings.Experimental.DHC.Loads` with the new coil model

**Comment by AntoineGautier** [comment]
@JayHuLBL This issue with OCT is fixed with d70513e.
I also added a start value for an iteration variable that the wet coil model introduces when configured in steady state, see 237bca2.
This is ready to merge if you are fine with those changes.

**Comment by JayHuLBL** [comment]
@AntoineGautier The changes look good to me.

**Pull request merged**
