### PR TITLE
Correct more misplaced each

### PR DESCRIPTION
**Pull request by perost**

### CODE REVIEW

**Comment by casella** [comment]
@mwetter, can you please get this through your CI and also apply it to the `maint_7.0.x` branch at your earliest convenience?

**Comment by mwetter** [comment]
@casella @perost : Thanks for the PR. This is now running through the CI for the maintenance and master branch through https://github.com/lbl-srg/modelica-buildings/pull/2444 and https://github.com/lbl-srg/modelica-buildings/pull/2445.
I will merge as soon as they pass.
The other PR from yesterday has been merged.

**Comment by casella** [comment]
Very good, thanks! The tests on our CI should show the improvement in a few days, when the libraries are updated and the library testsuite runs again.

**Comment by perost** [comment]
> Very good, thanks! The tests on our CI should show the improvement in a few days, when the libraries are updated and the library testsuite runs again.

This PR won't improve the coverage, it's just to get rid of a lot of warnings.

**Comment by casella** [comment]
Of course, I was referring to #2441 and #2442.

**Pull request closed without merging**
