### PR TITLE
Ibpsa merge1704

### PR DESCRIPTION
**Pull request by hcasperfu**
This PR is to merge changes made for https://github.com/ibpsa/modelica-ibpsa/issues/1704 from IBPSA.

### CODE REVIEW

**Review by mwetter — COMMENTED** [review]
@hcasperfu : can you please also update the conversion script in `Resources/Scripts/Conversion`

**Comment by hcasperfu** [comment]
@mwetter - I have never worked with the conversion script before. Can you please advise what I should do with it (and how I can verify I didn't break anything)?

Also in 4fc0ca7 I deleted the Nrpm component in `HydronicConfigurations`. FYI @AntoineGautier.

**Comment by mwetter** [comment]
@hcasperfu : Please see the Modelica Language Specification for the syntax of the conversion script (search for convertClass).
You can then build a model that uses the old library such as ```uses(Buildings(version="9.1.0"))```, and open the model while having Buildings 10.0.0 on `MODELICAPATH`. This then invokes the conversion script and updates your test model.

**Review by mwetter — COMMENTED** [review]
This is ready to merge when the conversion script is added.

**Pull request merged**
