### PR TITLE
Issue3379 fac mul dhw

### PR DESCRIPTION
**Pull request by dhblum**
This is for #3379.  It:
- Adds an example model and unit test results for ``Buildings.Experimental.DHC.Loads.Combined.BuildingTimeSeriesWithETS``
- Assigns ``dp_nominal`` to ETS pumps
- Applies ``facMul`` to domestic hot water load
- Corrects calculation of heat pump evaporator mass flow rate control in 
- Updates unit test results for ``Buildings.Experimental.DHC.Examples.Combined.SeriesConstantFlow`` and ``Buildings.Experimental.DHC.Examples.Combined.SeriesConstantFlow`` with particularly lower ETS pumping energy due to lower heat pump evaporator flow rates

Still to do:
- [x] Update release notes
- [x] Unit test passing
- [x] Review

### CODE REVIEW

**Comment by dhblum** [comment]
The added simple example model fails the unit test with OpenModelica.  The failure message in travis is:
```
*** Error: Simulation of Buildings.Experimental.DHC.Loads.Combined.Examples.BuildingTimeSeriesWithETS failed: ''omc Buildings.Experimental.DHC.Loads.Combined.Examples.BuildingTimeSeriesWithETS_simulate.mos' caused 'simulation terminated by an assertion at initialization'.'. 
```

But when I simulate in OMEdit locally, it finishes successfully and the results look correct.  But, there are a couple messages along the way:
```
Model error: Argument of log(dT2 / dT1) was -1 should be > 0

Non-Linear Solver try to handle a problem with a called assert.

The following assertion has been violated during initialization at time 0.000000 ((false)) --> "*** Warning in BuildingTimeSeriesWithETS.bui.bui.terUniHea.fan: Mover has per.etaHydMet=.Power_VolumeFlowRate or per.etaHydMet=.EulerNumber. This requires per.pressure to be provided. Because it is not, the model overrides this setting by using per.etaHydMet=.NotProvided."
```

Now one caveat is my OMEdit version is 1.21.0, not 1.22.0~dev-41-g8a5b18f-1.  In the past I've been able to update the version pretty easily, but this time when I try to update, v1.21.0 sticks around and I can't figure out yet how to remove it or use 1.22.0-dev instead.

@mwetter Do you have additional insights?

**Comment by mwetter** [comment]
@dhblum : If you configure your Linux as in https://openmodelica.org/download/download-linux/ for the nightly build and run `sudo apt-get update` followed by `sudo apt-get upgrade` it should install the latest version.
There have been quite some improvement in OpenModelica regarding division by zero.

**Comment by dhblum** [comment]
@mwetter Thanks.  Yes, this is what I followed.  It's worked in the past, but not this time.  For example:
```
:~$ sudo apt install openmodelica
[sudo] password for dhbubu20: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openmodelica is already the newest version (1.22.0~dev-51-ge506fbc-1).
The following packages were automatically installed and are no longer required:
  libfwupdplugin1 libxmlb1 ubuntu-advantage-desktop-daemon
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.
```
But then :
```
:~$ omc --version
OpenModelica 1.21.0
```
And running:
```
:~$ OMEdit
```
Opens:

Screen Shot 2023-05-04 at 11 45 09 AM

**Comment by dhblum** [comment]
@mwetter This is ready for your review.  Note that it addresses another issue I found in the course of this PR I describe here: https://github.com/lbl-srg/modelica-buildings/issues/3379#issuecomment-1550117128.

**Review by mwetter — APPROVED** [review]

**Comment by dhblum** [comment]
@mwetter Thank you!

**Comment by dhblum** [comment]
@mwetter A most recent master merge caused conflicts after you enabled auto-merge (squash).  I resolved the conflicts, but not sure if auto-merge is still enabled after I pushed the new changes.

**Comment by dhblum** [comment]
Tests are now failing because of a timeout on an openmodelica test of Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases9xx.Case920. I don't know what that's about, nothing in this PR is related to that model.

**Comment by mwetter** [comment]
I noticed `Case920` to timeout on other PRs as well. I increased the timeout and if that won't fix it will disable the simulation of this case for now. It works fine on my local installation.

**Comment by dhblum** [comment]
@mwetter Thank you!

**Pull request merged**
