### PR TITLE
Issue3230 add juntion

### LINKED ISSUE #3230: Add junction to ensure correct temperature sensor reading
In `Buildings.Examples.VAVReheat.BaseClasses.PartialHVAC`, in the case when there is a very small flow in the air duct, the mixed air temperature sensor `TMix` cannot quickly detect the air temperature in the duct. We will see different temperature reading from the sensor `TMix` and the `port_a2` of the `heaCoi`.

This issue is to add a junction (`Fluid.FixedResistances.Junction`) for mixing the return air and outdoor air. The junction introduces more dynamic so it will ensure the mixed air temperature sensor having consistent reading as the one in `port_a2` of `heaCoi`.

### PR DESCRIPTION
**Pull request by JayHuLBL**
This closes #3230.

### CODE REVIEW

**Comment by JayHuLBL** [comment]
@mwetter It's ready for your review.

**Comment by mwetter** [comment]
@JayHuLBL : Can you please check this PR. After merging the master which has the new mover model, `EnergyPlus_9_6_0.Examples.SmallOffice.Guideline36Summer` fails to simulate to the end time.

**Comment by JayHuLBL** [comment]
@mwetter 
I run the model `EnergyPlus_9_6_0.Examples.SmallOffice.Guideline36Summer` from both master and the merging branch in Dymola GUI, both indicates `SUCCESSFUL simulation of Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.Guideline36Summer`. In both runs, I can see the warning like `cvode: CVODE CVode At t = 1.68659e+07, mxstep steps taken before reaching tout.`. However, the merging branch gives more such warnings.

When running the unit test from the package `EnergyPlus_9_6_0.Examples.SmallOffice` in the merging branch, I did get the message below. But it is not the case in master branch.
```
*** Error: Simulation failed for 'RunScript("modelica://Buildings/Resources/Scripts/Dymola/ThermalZones/EnergyPlus_9_6_0/Examples/SmallOffice/Guideline36Summer.mos");'.
```
By checking into the unit test log file `failed-simulator-dymola.log`, it shows:
```
Failed
Warning: WARNINGS have been issued.
 = false
```

I will further look into how the failed information being issued.

**Comment by mwetter** [comment]
If you run the unit tests with `-d` you get the `.mos` script that causes the failure. See attached file for the settings.

[run_Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.Guideline36Summer.txt](https://github.com/lbl-srg/modelica-buildings/files/10772181/run_Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.Guideline36Summer.txt)

**Review by mwetter — APPROVED** [review]

**Comment by mwetter** [comment]
@JayHuLBL : If you update the reference results, then this is ready to be merged.

**Pull request merged**
