### PR TITLE
Refactor parameters for the usage of GMT extension  (#2750)

### LINKED ISSUE #2749: Revise `Experimental.DHC.CentralPlants.Example.Plant.mo` for GMT extension
Hi Dr.Hu @JayHuLBL , for the extension usage of GMT, I have made two minor changes for an existing example model `Experimental.DHC.CentralPlants.Example.Plant.mo` in MBL:

1. Add "replaceable" prefix for two parameters ("perChi", "pla") for new type redeclaring.
2. Add two more parameters ("dTApp" and "PFan_nominal") because they are also important parameters of the cooling plant which we wish to replace value for.

Here is the screenshots of what have been changed:

image

Could you please open a new branch for me to update these revision? Please let me know if you have any questions. Thanks!

### PR DESCRIPTION
**Pull request by mwetter**
This closes #2749

### CODE REVIEW

**Comment by mwetter** [comment]
@ChengnanShi-Work: Please let me know if you also need to have this applied to the maintenance branch for version 8.0.x

**Comment by ChengnanShi-Work** [comment]
> @ChengnanShi-Work: Please let me know if you also need to have this applied to the maintenance branch for version 8.0.x

Thank you Dr. Wetter@mwetter. Please correct me if I understand you wrong. Do you mean to applied this change to MBL version 8.0.x so that GMT could be able to use it once version 8.0.x is released?

**Comment by mwetter** [comment]
@ChengnanShi-Work : Yes, this is correct. Let me know if you need this for 8.0.x (currently it won't be part of it)

**Comment by ChengnanShi-Work** [comment]
@mwetter Thank you Dr, Wetter. After a short discussion with Dr. Zuo, I think we will need to have it for 8.0.x for better maintenance.

**Comment by mwetter** [comment]
@ChengnanShi-Work : Actually, that model (`Buildings/Experimental/DHC/CentralPlants/Cooling/Examples/Plant.mo `) is not part of the 8.0.0 release, and hence is not on the 8.0.x maintenance branch. So there is nothing to update for the 8.0.x release

**Comment by ChengnanShi-Work** [comment]
@mwetter Thanks for clearifying. In this case, I assume this model will be released for 9.0.0 maybe? And also, GMT needs to work on the master branch instead of the public released version of MBL for now?

**Comment by mwetter** [comment]
Yes, that's both correct as this model was not part of 8.0.0

**Comment by ChengnanShi-Work** [comment]
> Yes, that's both correct as this model was not part of 8.0.0

Thank you Dr. Wetter!

**Pull request merged**
